// Code generated by go generate; DO NOT EDIT.

// Copyright 2026 SudoSylabs
// SPDX-License-Identifier: AGPL-3.0-only

package retrylayer

import (
	"sync"

	"github.com/sudosylabs/proctor/server/store"
)

type retryStores struct {
	clusterDiscovery         store.ClusterDiscoveryStore
	clusterDiscoveryOnce     sync.Once
	examResource             store.ExamResourceStore
	examResourceOnce         sync.Once
	examRevision             store.ExamRevisionStore
	examRevisionOnce         sync.Once
	examStarterWorkspace     store.ExamStarterWorkspaceStore
	examStarterWorkspaceOnce sync.Once
	examAuthoring            store.ExamAuthoringStore
	examAuthoringOnce        sync.Once
	commandOutcome           store.CommandOutcomeStore
	commandOutcomeOnce       sync.Once
	job                      store.JobStore
	jobOnce                  sync.Once
	file                     store.FileStore
	fileOnce                 sync.Once
	institution              store.InstitutionStore
	institutionOnce          sync.Once
	academicUnit             store.AcademicUnitStore
	academicUnitOnce         sync.Once
	programme                store.ProgrammeStore
	programmeOnce            sync.Once
	programmeLevel           store.ProgrammeLevelStore
	programmeLevelOnce       sync.Once
	academicPeriod           store.AcademicPeriodStore
	academicPeriodOnce       sync.Once
	class                    store.ClassStore
	classOnce                sync.Once
	user                     store.UserStore
	userOnce                 sync.Once
	externalIdentity         store.ExternalIdentityStore
	externalIdentityOnce     sync.Once
	externalLoginState       store.ExternalLoginStateStore
	externalLoginStateOnce   sync.Once
	userToken                store.UserTokenStore
	userTokenOnce            sync.Once
	personalAccessToken      store.PersonalAccessTokenStore
	personalAccessTokenOnce  sync.Once
	mfa                      store.MFAStore
	mfaOnce                  sync.Once
	affiliation              store.AffiliationStore
	affiliationOnce          sync.Once
	academicUnitMember       store.AcademicUnitMemberStore
	academicUnitMemberOnce   sync.Once
	classMember              store.ClassMemberStore
	classMemberOnce          sync.Once
	passwordCredential       store.PasswordCredentialStore
	passwordCredentialOnce   sync.Once
	session                  store.SessionStore
	sessionOnce              sync.Once
	sessionCredential        store.SessionCredentialStore
	sessionCredentialOnce    sync.Once
	role                     store.RoleStore
	roleOnce                 sync.Once
	roleBinding              store.RoleBindingStore
	roleBindingOnce          sync.Once
	audit                    store.AuditStore
	auditOnce                sync.Once
	installation             store.InstallationStore
	installationOnce         sync.Once
}

type clusterDiscoveryStore struct {
	store.ClusterDiscoveryStore
	layer *Layer
}

type examResourceStore struct {
	store.ExamResourceStore
	layer *Layer
}

type examRevisionStore struct {
	store.ExamRevisionStore
	layer *Layer
}

type examStarterWorkspaceStore struct {
	store.ExamStarterWorkspaceStore
	layer *Layer
}

type examAuthoringStore struct {
	store.ExamAuthoringStore
	layer *Layer
}

type commandOutcomeStore struct {
	store.CommandOutcomeStore
	layer *Layer
}

type jobStore struct {
	store.JobStore
	layer *Layer
}

type fileStore struct {
	store.FileStore
	layer *Layer
}

type institutionStore struct {
	store.InstitutionStore
	layer *Layer
}

type academicUnitStore struct {
	store.AcademicUnitStore
	layer *Layer
}

type programmeStore struct {
	store.ProgrammeStore
	layer *Layer
}

type programmeLevelStore struct {
	store.ProgrammeLevelStore
	layer *Layer
}

type academicPeriodStore struct {
	store.AcademicPeriodStore
	layer *Layer
}

type classStore struct {
	store.ClassStore
	layer *Layer
}

type userStore struct {
	store.UserStore
	layer *Layer
}

type externalIdentityStore struct {
	store.ExternalIdentityStore
	layer *Layer
}

type externalLoginStateStore struct {
	store.ExternalLoginStateStore
	layer *Layer
}

type userTokenStore struct {
	store.UserTokenStore
	layer *Layer
}

type personalAccessTokenStore struct {
	store.PersonalAccessTokenStore
	layer *Layer
}

type mfaStore struct {
	store.MFAStore
	layer *Layer
}

type affiliationStore struct {
	store.AffiliationStore
	layer *Layer
}

type academicUnitMemberStore struct {
	store.AcademicUnitMemberStore
	layer *Layer
}

type classMemberStore struct {
	store.ClassMemberStore
	layer *Layer
}

type passwordCredentialStore struct {
	store.PasswordCredentialStore
	layer *Layer
}

type sessionStore struct {
	store.SessionStore
	layer *Layer
}

type sessionCredentialStore struct {
	store.SessionCredentialStore
	layer *Layer
}

type roleStore struct {
	store.RoleStore
	layer *Layer
}

type roleBindingStore struct {
	store.RoleBindingStore
	layer *Layer
}

type auditStore struct {
	store.AuditStore
	layer *Layer
}

type installationStore struct {
	store.InstallationStore
	layer *Layer
}

func (l *Layer) Institution() store.InstitutionStore {
	l.stores.institutionOnce.Do(func() {
		next := l.Store.Institution()
		if next != nil {
			l.stores.institution = &institutionStore{InstitutionStore: next, layer: l}
		}
	})
	return l.stores.institution
}

func (l *Layer) AcademicUnit() store.AcademicUnitStore {
	l.stores.academicUnitOnce.Do(func() {
		next := l.Store.AcademicUnit()
		if next != nil {
			l.stores.academicUnit = &academicUnitStore{AcademicUnitStore: next, layer: l}
		}
	})
	return l.stores.academicUnit
}

func (l *Layer) Programme() store.ProgrammeStore {
	l.stores.programmeOnce.Do(func() {
		next := l.Store.Programme()
		if next != nil {
			l.stores.programme = &programmeStore{ProgrammeStore: next, layer: l}
		}
	})
	return l.stores.programme
}

func (l *Layer) ProgrammeLevel() store.ProgrammeLevelStore {
	l.stores.programmeLevelOnce.Do(func() {
		next := l.Store.ProgrammeLevel()
		if next != nil {
			l.stores.programmeLevel = &programmeLevelStore{ProgrammeLevelStore: next, layer: l}
		}
	})
	return l.stores.programmeLevel
}

func (l *Layer) AcademicPeriod() store.AcademicPeriodStore {
	l.stores.academicPeriodOnce.Do(func() {
		next := l.Store.AcademicPeriod()
		if next != nil {
			l.stores.academicPeriod = &academicPeriodStore{AcademicPeriodStore: next, layer: l}
		}
	})
	return l.stores.academicPeriod
}

func (l *Layer) ExamAuthoring() store.ExamAuthoringStore {
	l.stores.examAuthoringOnce.Do(func() {
		next := l.Store.ExamAuthoring()
		if next != nil {
			l.stores.examAuthoring = &examAuthoringStore{ExamAuthoringStore: next, layer: l}
		}
	})
	return l.stores.examAuthoring
}

func (l *Layer) ExamRevision() store.ExamRevisionStore {
	l.stores.examRevisionOnce.Do(func() {
		next := l.Store.ExamRevision()
		if next != nil {
			l.stores.examRevision = &examRevisionStore{ExamRevisionStore: next, layer: l}
		}
	})
	return l.stores.examRevision
}

func (l *Layer) ExamResource() store.ExamResourceStore {
	l.stores.examResourceOnce.Do(func() {
		next := l.Store.ExamResource()
		if next != nil {
			l.stores.examResource = &examResourceStore{ExamResourceStore: next, layer: l}
		}
	})
	return l.stores.examResource
}

func (l *Layer) ExamStarterWorkspace() store.ExamStarterWorkspaceStore {
	l.stores.examStarterWorkspaceOnce.Do(func() {
		next := l.Store.ExamStarterWorkspace()
		if next != nil {
			l.stores.examStarterWorkspace = &examStarterWorkspaceStore{ExamStarterWorkspaceStore: next, layer: l}
		}
	})
	return l.stores.examStarterWorkspace
}

func (l *Layer) Class() store.ClassStore {
	l.stores.classOnce.Do(func() {
		next := l.Store.Class()
		if next != nil {
			l.stores.class = &classStore{ClassStore: next, layer: l}
		}
	})
	return l.stores.class
}

func (l *Layer) User() store.UserStore {
	l.stores.userOnce.Do(func() {
		next := l.Store.User()
		if next != nil {
			l.stores.user = &userStore{UserStore: next, layer: l}
		}
	})
	return l.stores.user
}

func (l *Layer) File() store.FileStore {
	l.stores.fileOnce.Do(func() {
		next := l.Store.File()
		if next != nil {
			l.stores.file = &fileStore{FileStore: next, layer: l}
		}
	})
	return l.stores.file
}

func (l *Layer) Job() store.JobStore {
	l.stores.jobOnce.Do(func() {
		next := l.Store.Job()
		if next != nil {
			l.stores.job = &jobStore{JobStore: next, layer: l}
		}
	})
	return l.stores.job
}

func (l *Layer) ExternalIdentity() store.ExternalIdentityStore {
	l.stores.externalIdentityOnce.Do(func() {
		next := l.Store.ExternalIdentity()
		if next != nil {
			l.stores.externalIdentity = &externalIdentityStore{ExternalIdentityStore: next, layer: l}
		}
	})
	return l.stores.externalIdentity
}

func (l *Layer) ExternalLoginState() store.ExternalLoginStateStore {
	l.stores.externalLoginStateOnce.Do(func() {
		next := l.Store.ExternalLoginState()
		if next != nil {
			l.stores.externalLoginState = &externalLoginStateStore{ExternalLoginStateStore: next, layer: l}
		}
	})
	return l.stores.externalLoginState
}

func (l *Layer) UserToken() store.UserTokenStore {
	l.stores.userTokenOnce.Do(func() {
		next := l.Store.UserToken()
		if next != nil {
			l.stores.userToken = &userTokenStore{UserTokenStore: next, layer: l}
		}
	})
	return l.stores.userToken
}

func (l *Layer) PersonalAccessToken() store.PersonalAccessTokenStore {
	l.stores.personalAccessTokenOnce.Do(func() {
		next := l.Store.PersonalAccessToken()
		if next != nil {
			l.stores.personalAccessToken = &personalAccessTokenStore{PersonalAccessTokenStore: next, layer: l}
		}
	})
	return l.stores.personalAccessToken
}

func (l *Layer) MFA() store.MFAStore {
	l.stores.mfaOnce.Do(func() {
		next := l.Store.MFA()
		if next != nil {
			l.stores.mfa = &mfaStore{MFAStore: next, layer: l}
		}
	})
	return l.stores.mfa
}

func (l *Layer) Affiliation() store.AffiliationStore {
	l.stores.affiliationOnce.Do(func() {
		next := l.Store.Affiliation()
		if next != nil {
			l.stores.affiliation = &affiliationStore{AffiliationStore: next, layer: l}
		}
	})
	return l.stores.affiliation
}

func (l *Layer) AcademicUnitMember() store.AcademicUnitMemberStore {
	l.stores.academicUnitMemberOnce.Do(func() {
		next := l.Store.AcademicUnitMember()
		if next != nil {
			l.stores.academicUnitMember = &academicUnitMemberStore{AcademicUnitMemberStore: next, layer: l}
		}
	})
	return l.stores.academicUnitMember
}

func (l *Layer) ClassMember() store.ClassMemberStore {
	l.stores.classMemberOnce.Do(func() {
		next := l.Store.ClassMember()
		if next != nil {
			l.stores.classMember = &classMemberStore{ClassMemberStore: next, layer: l}
		}
	})
	return l.stores.classMember
}

func (l *Layer) PasswordCredential() store.PasswordCredentialStore {
	l.stores.passwordCredentialOnce.Do(func() {
		next := l.Store.PasswordCredential()
		if next != nil {
			l.stores.passwordCredential = &passwordCredentialStore{PasswordCredentialStore: next, layer: l}
		}
	})
	return l.stores.passwordCredential
}

func (l *Layer) Session() store.SessionStore {
	l.stores.sessionOnce.Do(func() {
		next := l.Store.Session()
		if next != nil {
			l.stores.session = &sessionStore{SessionStore: next, layer: l}
		}
	})
	return l.stores.session
}

func (l *Layer) SessionCredential() store.SessionCredentialStore {
	l.stores.sessionCredentialOnce.Do(func() {
		next := l.Store.SessionCredential()
		if next != nil {
			l.stores.sessionCredential = &sessionCredentialStore{SessionCredentialStore: next, layer: l}
		}
	})
	return l.stores.sessionCredential
}

func (l *Layer) Role() store.RoleStore {
	l.stores.roleOnce.Do(func() {
		next := l.Store.Role()
		if next != nil {
			l.stores.role = &roleStore{RoleStore: next, layer: l}
		}
	})
	return l.stores.role
}

func (l *Layer) RoleBinding() store.RoleBindingStore {
	l.stores.roleBindingOnce.Do(func() {
		next := l.Store.RoleBinding()
		if next != nil {
			l.stores.roleBinding = &roleBindingStore{RoleBindingStore: next, layer: l}
		}
	})
	return l.stores.roleBinding
}

func (l *Layer) Audit() store.AuditStore {
	l.stores.auditOnce.Do(func() {
		next := l.Store.Audit()
		if next != nil {
			l.stores.audit = &auditStore{AuditStore: next, layer: l}
		}
	})
	return l.stores.audit
}

func (l *Layer) Installation() store.InstallationStore {
	l.stores.installationOnce.Do(func() {
		next := l.Store.Installation()
		if next != nil {
			l.stores.installation = &installationStore{InstallationStore: next, layer: l}
		}
	})
	return l.stores.installation
}

func (l *Layer) ClusterDiscovery() store.ClusterDiscoveryStore {
	l.stores.clusterDiscoveryOnce.Do(func() {
		next := l.Store.ClusterDiscovery()
		if next != nil {
			l.stores.clusterDiscovery = &clusterDiscoveryStore{ClusterDiscoveryStore: next, layer: l}
		}
	})
	return l.stores.clusterDiscovery
}

func (l *Layer) CommandOutcome() store.CommandOutcomeStore {
	l.stores.commandOutcomeOnce.Do(func() {
		next := l.Store.CommandOutcome()
		if next != nil {
			l.stores.commandOutcome = &commandOutcomeStore{CommandOutcomeStore: next, layer: l}
		}
	})
	return l.stores.commandOutcome
}

var (
	_ store.Store                     = (*Layer)(nil)
	_ store.ClusterDiscoveryStore     = (*clusterDiscoveryStore)(nil)
	_ store.ExamResourceStore         = (*examResourceStore)(nil)
	_ store.ExamRevisionStore         = (*examRevisionStore)(nil)
	_ store.ExamStarterWorkspaceStore = (*examStarterWorkspaceStore)(nil)
	_ store.ExamAuthoringStore        = (*examAuthoringStore)(nil)
	_ store.CommandOutcomeStore       = (*commandOutcomeStore)(nil)
	_ store.JobStore                  = (*jobStore)(nil)
	_ store.FileStore                 = (*fileStore)(nil)
	_ store.InstitutionStore          = (*institutionStore)(nil)
	_ store.AcademicUnitStore         = (*academicUnitStore)(nil)
	_ store.ProgrammeStore            = (*programmeStore)(nil)
	_ store.ProgrammeLevelStore       = (*programmeLevelStore)(nil)
	_ store.AcademicPeriodStore       = (*academicPeriodStore)(nil)
	_ store.ClassStore                = (*classStore)(nil)
	_ store.UserStore                 = (*userStore)(nil)
	_ store.ExternalIdentityStore     = (*externalIdentityStore)(nil)
	_ store.ExternalLoginStateStore   = (*externalLoginStateStore)(nil)
	_ store.UserTokenStore            = (*userTokenStore)(nil)
	_ store.PersonalAccessTokenStore  = (*personalAccessTokenStore)(nil)
	_ store.MFAStore                  = (*mfaStore)(nil)
	_ store.AffiliationStore          = (*affiliationStore)(nil)
	_ store.AcademicUnitMemberStore   = (*academicUnitMemberStore)(nil)
	_ store.ClassMemberStore          = (*classMemberStore)(nil)
	_ store.PasswordCredentialStore   = (*passwordCredentialStore)(nil)
	_ store.SessionStore              = (*sessionStore)(nil)
	_ store.SessionCredentialStore    = (*sessionCredentialStore)(nil)
	_ store.RoleStore                 = (*roleStore)(nil)
	_ store.RoleBindingStore          = (*roleBindingStore)(nil)
	_ store.AuditStore                = (*auditStore)(nil)
	_ store.InstallationStore         = (*installationStore)(nil)
)
