// Copyright 2026 SudoSylabs
// SPDX-License-Identifier: AGPL-3.0-only

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strings"
	"unicode"
)

func main() {
	source := flag.String("source", "id.go", "handwritten typed-ID declarations")
	output := flag.String("output", "id_gen.go", "generated output path")
	flag.Parse()

	declared, err := declaredIDTypes(*source)
	if err != nil {
		fatal(err)
	}
	if err := validateDeclarations(declared, entityIDs); err != nil {
		fatal(err)
	}
	generated, err := render(entityIDs)
	if err != nil {
		fatal(err)
	}
	if err := os.WriteFile(*output, generated, 0o644); err != nil {
		fatal(fmt.Errorf("write %s: %w", *output, err))
	}
}

func declaredIDTypes(path string) ([]string, error) {
	parsed, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.SkipObjectResolution)
	if err != nil {
		return nil, fmt.Errorf("parse typed-ID declarations from %s: %w", path, err)
	}
	var result []string
	for _, declaration := range parsed.Decls {
		general, ok := declaration.(*ast.GenDecl)
		if !ok || general.Tok != token.TYPE {
			continue
		}
		for _, raw := range general.Specs {
			spec := raw.(*ast.TypeSpec)
			if !strings.HasSuffix(spec.Name.Name, "ID") {
				continue
			}
			underlying, ok := spec.Type.(*ast.Ident)
			if !ok || underlying.Name != "string" || spec.Assign.IsValid() {
				return nil, fmt.Errorf("typed-ID declaration %s must be a distinct string-backed type", spec.Name.Name)
			}
			result = append(result, spec.Name.Name)
		}
	}
	return result, nil
}

func validateDeclarations(declared []string, specs []idSpec) error {
	if len(declared) != len(specs) {
		return fmt.Errorf("typed-ID declarations contain %d types but catalog contains %d", len(declared), len(specs))
	}
	for index, declaredType := range declared {
		if declaredType != specs[index].typeName {
			return fmt.Errorf("typed-ID declaration %d is %q but catalog declares %q", index, declaredType, specs[index].typeName)
		}
	}
	return nil
}

func render(specs []idSpec) ([]byte, error) {
	if err := validateCatalog(specs); err != nil {
		return nil, err
	}

	var output bytes.Buffer
	output.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	output.WriteString("// Copyright 2026 SudoSylabs\n// SPDX-License-Identifier: AGPL-3.0-only\n\n")
	output.WriteString("package model\n\n")

	for _, spec := range specs {
		fmt.Fprintf(&output, "// New%s returns a freshly generated %s identifier.\n", spec.typeName, spec.constructorSubject)
		fmt.Fprintf(&output, "func New%s() %s { return %s(NewId()) }\n\n", spec.typeName, spec.typeName, spec.typeName)
	}
	for _, spec := range specs {
		fmt.Fprintf(&output, "// Parse%s validates and converts the shared identifier representation.\n", spec.typeName)
		fmt.Fprintf(&output, "func Parse%s(value string) (%s, error) {\n", spec.typeName, spec.typeName)
		fmt.Fprintf(&output, "\treturn parseID[%s](value, %q)\n", spec.typeName, spec.fieldName)
		output.WriteString("}\n\n")
	}
	for _, spec := range specs {
		fmt.Fprintf(&output, "// IsZero reports whether the %s is the empty zero value.\n", spec.constructorSubject)
		fmt.Fprintf(&output, "func (id %s) IsZero() bool { return id == \"\" }\n\n", spec.typeName)
	}
	for _, spec := range specs {
		fmt.Fprintf(&output, "// IsValid reports whether the %s is a canonical non-zero ID.\n", spec.constructorSubject)
		fmt.Fprintf(&output, "func (id %s) IsValid() bool { return IsValidId(string(id)) }\n\n", spec.typeName)
	}
	for _, spec := range specs {
		fmt.Fprintf(&output, "// String returns the %s wire/database representation.\n", spec.constructorSubject)
		fmt.Fprintf(&output, "func (id %s) String() string { return string(id) }\n\n", spec.typeName)
	}
	for _, spec := range specs {
		fmt.Fprintf(&output, "// MarshalText encodes the %s as its canonical string.\n", spec.constructorSubject)
		fmt.Fprintf(&output, "func (id %s) MarshalText() ([]byte, error) { return marshalID(id) }\n\n", spec.typeName)
	}
	for _, spec := range specs {
		fmt.Fprintf(&output, "// UnmarshalText decodes and validates the %s when non-empty.\n", spec.constructorSubject)
		fmt.Fprintf(&output, "func (id *%s) UnmarshalText(data []byte) error {\n", spec.typeName)
		fmt.Fprintf(&output, "\treturn unmarshalID(id, data, Parse%s)\n", spec.typeName)
		output.WriteString("}\n\n")
	}
	for _, spec := range specs {
		fmt.Fprintf(&output, "// MarshalJSON encodes the %s as a JSON string.\n", spec.constructorSubject)
		fmt.Fprintf(&output, "func (id %s) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }\n\n", spec.typeName)
	}
	for _, spec := range specs {
		fmt.Fprintf(&output, "// UnmarshalJSON decodes a JSON string into the %s.\n", spec.constructorSubject)
		fmt.Fprintf(&output, "func (id *%s) UnmarshalJSON(data []byte) error {\n", spec.typeName)
		fmt.Fprintf(&output, "\treturn unmarshalIDJSON(id, data, Parse%s)\n", spec.typeName)
		output.WriteString("}\n\n")
	}

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated typed IDs: %w\n%s", err, output.Bytes())
	}
	return formatted, nil
}

func validateCatalog(specs []idSpec) error {
	if len(specs) == 0 {
		return fmt.Errorf("typed-ID catalog is empty")
	}
	seenTypes := make(map[string]struct{}, len(specs))
	seenFields := make(map[string]struct{}, len(specs))
	for index, spec := range specs {
		if !validTypeName(spec.typeName) {
			return fmt.Errorf("typed-ID catalog entry %d has invalid type name %q", index, spec.typeName)
		}
		if !validFieldName(spec.fieldName) {
			return fmt.Errorf("typed-ID catalog entry %d has invalid field name %q", index, spec.fieldName)
		}
		if strings.TrimSpace(spec.constructorSubject) == "" {
			return fmt.Errorf("typed-ID catalog entry %d has empty constructor subject", index)
		}
		if _, exists := seenTypes[spec.typeName]; exists {
			return fmt.Errorf("typed-ID catalog contains duplicate type %q", spec.typeName)
		}
		if _, exists := seenFields[spec.fieldName]; exists {
			return fmt.Errorf("typed-ID catalog contains duplicate field %q", spec.fieldName)
		}
		seenTypes[spec.typeName] = struct{}{}
		seenFields[spec.fieldName] = struct{}{}
	}
	return nil
}

func validTypeName(value string) bool {
	if !strings.HasSuffix(value, "ID") || value == "ID" {
		return false
	}
	for index, character := range value {
		if index == 0 && !unicode.IsUpper(character) {
			return false
		}
		if !unicode.IsLetter(character) && !unicode.IsDigit(character) {
			return false
		}
	}
	return true
}

func validFieldName(value string) bool {
	if !strings.HasSuffix(value, "_id") || value == "_id" {
		return false
	}
	for _, character := range value {
		if (character < 'a' || character > 'z') && (character < '0' || character > '9') && character != '_' {
			return false
		}
	}
	return true
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
