// Copyright 2026 SudoSylabs
// SPDX-License-Identifier: AGPL-3.0-only

// Human-owned source for the Proctor webapp design system.
//
// Change values here, explain durable meaning in ../DESIGN_SYSTEM.md, then run
// `npm run design-system:generate`. The generated CSS is an adapter, not a
// second token authority.

const palette = {
  ink: '#161616',
  paper: '#ffffff',
  purple: '#5c00aa',
  teal: '#0b766e',
  amber: '#95520d',
  coral: '#b4233c',
};

export const designTokens = {
  id: 'proctor-web-v1',

  typography: {
    display: {
      name: 'IBM Plex Sans Condensed',
      family:
        '"IBM Plex Sans Condensed", "Arial Narrow", "Segoe UI", sans-serif',
      files: {
        500: '@fontsource/ibm-plex-sans-condensed/files/ibm-plex-sans-condensed-latin-500-normal.woff2',
        600: '@fontsource/ibm-plex-sans-condensed/files/ibm-plex-sans-condensed-latin-600-normal.woff2',
      },
      weights: [500, 600],
    },
    text: {
      name: 'IBM Plex Sans',
      family: '"IBM Plex Sans", "Segoe UI", Arial, sans-serif',
      files: {
        400: '@fontsource/ibm-plex-sans/files/ibm-plex-sans-latin-400-normal.woff2',
        500: '@fontsource/ibm-plex-sans/files/ibm-plex-sans-latin-500-normal.woff2',
        600: '@fontsource/ibm-plex-sans/files/ibm-plex-sans-latin-600-normal.woff2',
        700: '@fontsource/ibm-plex-sans/files/ibm-plex-sans-latin-700-normal.woff2',
      },
      weights: [400, 500, 600, 700],
    },
    mono: {
      name: 'IBM Plex Mono',
      family:
        '"IBM Plex Mono", "SFMono-Regular", Consolas, "Liberation Mono", monospace',
      files: {
        400: '@fontsource/ibm-plex-mono/files/ibm-plex-mono-latin-400-normal.woff2',
        600: '@fontsource/ibm-plex-mono/files/ibm-plex-mono-latin-600-normal.woff2',
      },
      weights: [400, 600],
    },
  },

  system: {
    space: {
      0: '0',
      1: '0.25rem',
      2: '0.5rem',
      3: '0.75rem',
      4: '1rem',
      5: '1.5rem',
      6: '2rem',
      7: '3rem',
      8: '4rem',
      9: '6rem',
    },
    fontSize: {
      caption: '0.75rem',
      label: '0.8125rem',
      bodySmall: '0.875rem',
      body: '1rem',
      bodyLarge: '1.125rem',
      headingSmall: '1.25rem',
      headingMedium: '1.5rem',
      headingLarge: '2rem',
      display: 'clamp(2.25rem, 1.8rem + 1.5vw, 3.5rem)',
    },
    lineHeight: {
      caption: '1.4',
      label: '1.35',
      bodySmall: '1.55',
      body: '1.6',
      bodyLarge: '1.55',
      headingSmall: '1.35',
      headingMedium: '1.25',
      headingLarge: '1.15',
      display: '1.02',
    },
    fontWeight: {
      regular: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
    },
    letterSpacing: {
      display: '-0.018em',
      heading: '-0.012em',
      body: '0',
      label: '0.01em',
    },
    radius: {
      none: '0',
      control: '0.375rem',
      card: '0.75rem',
      panel: '1rem',
      round: '999px',
    },
    borderWidth: {
      hairline: '1px',
      strong: '2px',
      focus: '3px',
    },
    controlSize: {
      compact: '2.5rem',
      default: '2.75rem',
      comfortable: '3rem',
    },
    iconSize: {
      small: '1rem',
      default: '1.25rem',
      large: '1.5rem',
    },
    measure: {
      prose: '74ch',
      form: '36rem',
      content: '72rem',
      application: '90rem',
      sidebar: '18rem',
    },
    duration: {
      immediate: '80ms',
      fast: '140ms',
      moderate: '200ms',
      slow: '320ms',
    },
    easing: {
      standard: 'cubic-bezier(0.2, 0, 0, 1)',
      enter: 'cubic-bezier(0, 0, 0, 1)',
      exit: 'cubic-bezier(0.3, 0, 1, 1)',
    },
    layer: {
      base: '0',
      sticky: '10',
      popover: '20',
      overlay: '30',
      dialog: '40',
      notification: '50',
    },
  },

  breakpoints: {
    compact: '30rem',
    content: '48rem',
    wide: '72rem',
    maximum: '90rem',
  },

  themes: {
    light: {
      label: 'Light',
      colorScheme: 'light',
      color: {
        'background-canvas': palette.paper,
        'background-subtle': '#f7f5f9',
        'background-surface': palette.paper,
        'background-raised': palette.paper,
        'background-inverse': '#17121a',
        'foreground-default': palette.ink,
        'foreground-subtle': '#49434f',
        'foreground-muted': '#655f69',
        'foreground-disabled': '#8a838f',
        'foreground-inverse': '#f8f6fa',
        'foreground-link': palette.purple,
        'border-default': '#e1dce5',
        'border-strong': '#c8c0ce',
        'border-interactive': '#8e64ad',
        'focus-ring': palette.purple,
        'action-primary': palette.purple,
        'action-primary-hover': '#470082',
        'action-primary-active': '#370065',
        'action-primary-disabled': '#e1dce5',
        'action-on-primary': palette.paper,
        'action-secondary': palette.paper,
        'action-secondary-hover': '#f3eafb',
        'action-secondary-active': '#e8d7f4',
        'action-on-secondary': palette.purple,
        'state-info': palette.purple,
        'state-info-surface': '#f3eafb',
        'state-success': palette.teal,
        'state-success-surface': '#e7f5f1',
        'state-warning': palette.amber,
        'state-warning-surface': '#fff3e5',
        'state-danger': palette.coral,
        'state-danger-surface': '#fff0f1',
        'selection-background': palette.purple,
        'selection-foreground': palette.paper,
        scrim: 'rgb(20 12 26 / 58%)',
        skeleton: '#ebe7ee',
      },
      shadow: {
        raised: '0 1px 2px rgb(45 20 62 / 8%), 0 4px 12px rgb(45 20 62 / 6%)',
        overlay: '0 12px 32px rgb(45 20 62 / 16%)',
        dialog: '0 20px 60px rgb(45 20 62 / 22%)',
      },
    },
    dark: {
      label: 'Dark',
      colorScheme: 'dark',
      color: {
        'background-canvas': '#111111',
        'background-subtle': '#171717',
        'background-surface': '#1c1c1c',
        'background-raised': '#242424',
        'background-inverse': '#f5f3ff',
        'foreground-default': '#f5f3ff',
        'foreground-subtle': '#d4d4d8',
        'foreground-muted': '#a1a1aa',
        'foreground-disabled': '#71717a',
        'foreground-inverse': '#0a0a0a',
        'foreground-link': '#e9d5ff',
        'border-default': '#2e2e2e',
        'border-strong': '#3f3f46',
        'border-interactive': '#71717a',
        'focus-ring': '#f5f3ff',
        'action-primary': '#a855f7',
        'action-primary-hover': '#c084fc',
        'action-primary-active': '#a350f0',
        'action-primary-disabled': '#2e2e2e',
        'action-on-primary': '#0a0a0a',
        'action-secondary': '#1c1c1c',
        'action-secondary-hover': '#242424',
        'action-secondary-active': '#2e2e2e',
        'action-on-secondary': '#e9d5ff',
        'state-info': '#a855f7',
        'state-info-surface': '#1f112c',
        'state-success': '#3ecf8e',
        'state-success-surface': '#0f241c',
        'state-warning': '#f5b942',
        'state-warning-surface': '#2a2110',
        'state-danger': '#f87171',
        'state-danger-surface': '#2a1218',
        'selection-background': '#a855f7',
        'selection-foreground': '#0a0a0a',
        scrim: 'rgb(0 0 0 / 72%)',
        skeleton: '#2e2e2e',
      },
      shadow: {
        raised: '0 1px 2px rgb(0 0 0 / 24%), 0 4px 14px rgb(0 0 0 / 20%)',
        overlay: '0 12px 36px rgb(0 0 0 / 36%)',
        dialog: '0 20px 64px rgb(0 0 0 / 48%)',
      },
    },
  },
};
