# ---------------------------------------------------------------------------------------------
# Copyright (c) 2026 Sudosy Labs. All rights reserved.
# Licensed under the GNU Affero General Public License, version 3 only.
# See LICENSE in the server module root for license information.
# SPDX-License-Identifier: AGPL-3.0-only
# ---------------------------------------------------------------------------------------------

.PHONY: install generate check test

install:
	npm ci

generate:
	npm run generate

check:
	npm run check

test:
	npm test
