// Code generated by go generate; DO NOT EDIT.

// Copyright 2026 SudoSylabs
// SPDX-License-Identifier: AGPL-3.0-only

package model

// NewInstitutionID returns a freshly generated institution identifier.
func NewInstitutionID() InstitutionID { return InstitutionID(NewId()) }

// NewAcademicUnitID returns a freshly generated academic-unit identifier.
func NewAcademicUnitID() AcademicUnitID { return AcademicUnitID(NewId()) }

// NewProgrammeID returns a freshly generated programme identifier.
func NewProgrammeID() ProgrammeID { return ProgrammeID(NewId()) }

// NewProgrammeLevelID returns a freshly generated programme-level identifier.
func NewProgrammeLevelID() ProgrammeLevelID { return ProgrammeLevelID(NewId()) }

// NewClassID returns a freshly generated class identifier.
func NewClassID() ClassID { return ClassID(NewId()) }

// NewAcademicPeriodID returns a freshly generated academic-period identifier.
func NewAcademicPeriodID() AcademicPeriodID { return AcademicPeriodID(NewId()) }

// NewExamID returns a freshly generated exam identifier.
func NewExamID() ExamID { return ExamID(NewId()) }

// NewExamRevisionID returns a freshly generated exam-revision identifier.
func NewExamRevisionID() ExamRevisionID { return ExamRevisionID(NewId()) }

// NewExamSittingID returns a freshly generated exam-sitting identifier.
func NewExamSittingID() ExamSittingID { return ExamSittingID(NewId()) }

// NewExamResourceID returns a freshly generated exam-resource identifier.
func NewExamResourceID() ExamResourceID { return ExamResourceID(NewId()) }

// NewExamCorrectionResourceStageID returns a freshly generated exam-correction-resource-stage identifier.
func NewExamCorrectionResourceStageID() ExamCorrectionResourceStageID {
	return ExamCorrectionResourceStageID(NewId())
}

// NewExamAttemptID returns a freshly generated exam-attempt identifier.
func NewExamAttemptID() ExamAttemptID { return ExamAttemptID(NewId()) }

// NewExamAttemptWorkspaceID returns a freshly generated exam-attempt-workspace identifier.
func NewExamAttemptWorkspaceID() ExamAttemptWorkspaceID { return ExamAttemptWorkspaceID(NewId()) }

// NewAttemptParticipationID returns a freshly generated attempt-participation identifier.
func NewAttemptParticipationID() AttemptParticipationID { return AttemptParticipationID(NewId()) }

// NewAttemptConnectionID returns a freshly generated attempt-connection identifier.
func NewAttemptConnectionID() AttemptConnectionID { return AttemptConnectionID(NewId()) }

// NewFocusLossSignalID returns a freshly generated focus-loss-signal identifier.
func NewFocusLossSignalID() FocusLossSignalID { return FocusLossSignalID(NewId()) }

// NewIntegrityEvidenceID returns a freshly generated integrity-evidence identifier.
func NewIntegrityEvidenceID() IntegrityEvidenceID { return IntegrityEvidenceID(NewId()) }

// NewIntegrityFlagID returns a freshly generated integrity-flag identifier.
func NewIntegrityFlagID() IntegrityFlagID { return IntegrityFlagID(NewId()) }

// NewAttemptSuspensionID returns a freshly generated attempt-suspension identifier.
func NewAttemptSuspensionID() AttemptSuspensionID { return AttemptSuspensionID(NewId()) }

// NewAttemptWorkspaceEntryID returns a freshly generated attempt-workspace-entry identifier.
func NewAttemptWorkspaceEntryID() AttemptWorkspaceEntryID { return AttemptWorkspaceEntryID(NewId()) }

// NewAttemptWorkspaceObjectID returns a freshly generated attempt-workspace-object identifier.
func NewAttemptWorkspaceObjectID() AttemptWorkspaceObjectID { return AttemptWorkspaceObjectID(NewId()) }

// NewStarterWorkspaceEntryID returns a freshly generated starter-workspace-entry identifier.
func NewStarterWorkspaceEntryID() StarterWorkspaceEntryID { return StarterWorkspaceEntryID(NewId()) }

// NewStarterWorkspaceObjectID returns a freshly generated starter-workspace-object identifier.
func NewStarterWorkspaceObjectID() StarterWorkspaceObjectID { return StarterWorkspaceObjectID(NewId()) }

// NewUserID returns a freshly generated user identifier.
func NewUserID() UserID { return UserID(NewId()) }

// NewSessionID returns a freshly generated session identifier.
func NewSessionID() SessionID { return SessionID(NewId()) }

// NewSessionCredentialID returns a freshly generated session-credential identifier.
func NewSessionCredentialID() SessionCredentialID { return SessionCredentialID(NewId()) }

// NewRoleID returns a freshly generated role identifier.
func NewRoleID() RoleID { return RoleID(NewId()) }

// NewRoleBindingID returns a freshly generated role-binding identifier.
func NewRoleBindingID() RoleBindingID { return RoleBindingID(NewId()) }

// NewAffiliationID returns a freshly generated affiliation identifier.
func NewAffiliationID() AffiliationID { return AffiliationID(NewId()) }

// NewAcademicUnitMemberID returns a freshly generated academic-unit-member identifier.
func NewAcademicUnitMemberID() AcademicUnitMemberID { return AcademicUnitMemberID(NewId()) }

// NewClassMemberID returns a freshly generated class-member identifier.
func NewClassMemberID() ClassMemberID { return ClassMemberID(NewId()) }

// NewExternalIdentityID returns a freshly generated external-identity identifier.
func NewExternalIdentityID() ExternalIdentityID { return ExternalIdentityID(NewId()) }

// NewPasswordCredentialID returns a freshly generated password-credential identifier.
func NewPasswordCredentialID() PasswordCredentialID { return PasswordCredentialID(NewId()) }

// NewPersonalAccessTokenID returns a freshly generated personal-access-token identifier.
func NewPersonalAccessTokenID() PersonalAccessTokenID { return PersonalAccessTokenID(NewId()) }

// NewUserTokenID returns a freshly generated user-token identifier.
func NewUserTokenID() UserTokenID { return UserTokenID(NewId()) }

// NewMFACredentialID returns a freshly generated MFA credential identifier.
func NewMFACredentialID() MFACredentialID { return MFACredentialID(NewId()) }

// NewMFARecoveryCodeID returns a freshly generated MFA recovery-code identifier.
func NewMFARecoveryCodeID() MFARecoveryCodeID { return MFARecoveryCodeID(NewId()) }

// NewAuditEventID returns a freshly generated audit-event identifier.
func NewAuditEventID() AuditEventID { return AuditEventID(NewId()) }

// NewExternalLoginStateID returns a freshly generated external-login-state identifier.
func NewExternalLoginStateID() ExternalLoginStateID { return ExternalLoginStateID(NewId()) }

// NewFileEntryID returns a freshly generated file-entry identifier.
func NewFileEntryID() FileEntryID { return FileEntryID(NewId()) }

// NewFileRevisionID returns a freshly generated file-revision identifier.
func NewFileRevisionID() FileRevisionID { return FileRevisionID(NewId()) }

// NewFileRenditionID returns a freshly generated file-rendition identifier.
func NewFileRenditionID() FileRenditionID { return FileRenditionID(NewId()) }

// NewUploadLeaseID returns a freshly generated upload-lease identifier.
func NewUploadLeaseID() UploadLeaseID { return UploadLeaseID(NewId()) }

// ParseInstitutionID validates and converts the shared identifier representation.
func ParseInstitutionID(value string) (InstitutionID, error) {
	return parseID[InstitutionID](value, "institution_id")
}

// ParseAcademicUnitID validates and converts the shared identifier representation.
func ParseAcademicUnitID(value string) (AcademicUnitID, error) {
	return parseID[AcademicUnitID](value, "academic_unit_id")
}

// ParseProgrammeID validates and converts the shared identifier representation.
func ParseProgrammeID(value string) (ProgrammeID, error) {
	return parseID[ProgrammeID](value, "programme_id")
}

// ParseProgrammeLevelID validates and converts the shared identifier representation.
func ParseProgrammeLevelID(value string) (ProgrammeLevelID, error) {
	return parseID[ProgrammeLevelID](value, "programme_level_id")
}

// ParseClassID validates and converts the shared identifier representation.
func ParseClassID(value string) (ClassID, error) {
	return parseID[ClassID](value, "class_id")
}

// ParseAcademicPeriodID validates and converts the shared identifier representation.
func ParseAcademicPeriodID(value string) (AcademicPeriodID, error) {
	return parseID[AcademicPeriodID](value, "academic_period_id")
}

// ParseExamID validates and converts the shared identifier representation.
func ParseExamID(value string) (ExamID, error) {
	return parseID[ExamID](value, "exam_id")
}

// ParseExamRevisionID validates and converts the shared identifier representation.
func ParseExamRevisionID(value string) (ExamRevisionID, error) {
	return parseID[ExamRevisionID](value, "exam_revision_id")
}

// ParseExamSittingID validates and converts the shared identifier representation.
func ParseExamSittingID(value string) (ExamSittingID, error) {
	return parseID[ExamSittingID](value, "exam_sitting_id")
}

// ParseExamResourceID validates and converts the shared identifier representation.
func ParseExamResourceID(value string) (ExamResourceID, error) {
	return parseID[ExamResourceID](value, "exam_resource_id")
}

// ParseExamCorrectionResourceStageID validates and converts the shared identifier representation.
func ParseExamCorrectionResourceStageID(value string) (ExamCorrectionResourceStageID, error) {
	return parseID[ExamCorrectionResourceStageID](value, "exam_correction_resource_stage_id")
}

// ParseExamAttemptID validates and converts the shared identifier representation.
func ParseExamAttemptID(value string) (ExamAttemptID, error) {
	return parseID[ExamAttemptID](value, "exam_attempt_id")
}

// ParseExamAttemptWorkspaceID validates and converts the shared identifier representation.
func ParseExamAttemptWorkspaceID(value string) (ExamAttemptWorkspaceID, error) {
	return parseID[ExamAttemptWorkspaceID](value, "exam_attempt_workspace_id")
}

// ParseAttemptParticipationID validates and converts the shared identifier representation.
func ParseAttemptParticipationID(value string) (AttemptParticipationID, error) {
	return parseID[AttemptParticipationID](value, "attempt_participation_id")
}

// ParseAttemptConnectionID validates and converts the shared identifier representation.
func ParseAttemptConnectionID(value string) (AttemptConnectionID, error) {
	return parseID[AttemptConnectionID](value, "attempt_connection_id")
}

// ParseFocusLossSignalID validates and converts the shared identifier representation.
func ParseFocusLossSignalID(value string) (FocusLossSignalID, error) {
	return parseID[FocusLossSignalID](value, "focus_loss_signal_id")
}

// ParseIntegrityEvidenceID validates and converts the shared identifier representation.
func ParseIntegrityEvidenceID(value string) (IntegrityEvidenceID, error) {
	return parseID[IntegrityEvidenceID](value, "integrity_evidence_id")
}

// ParseIntegrityFlagID validates and converts the shared identifier representation.
func ParseIntegrityFlagID(value string) (IntegrityFlagID, error) {
	return parseID[IntegrityFlagID](value, "integrity_flag_id")
}

// ParseAttemptSuspensionID validates and converts the shared identifier representation.
func ParseAttemptSuspensionID(value string) (AttemptSuspensionID, error) {
	return parseID[AttemptSuspensionID](value, "attempt_suspension_id")
}

// ParseAttemptWorkspaceEntryID validates and converts the shared identifier representation.
func ParseAttemptWorkspaceEntryID(value string) (AttemptWorkspaceEntryID, error) {
	return parseID[AttemptWorkspaceEntryID](value, "attempt_workspace_entry_id")
}

// ParseAttemptWorkspaceObjectID validates and converts the shared identifier representation.
func ParseAttemptWorkspaceObjectID(value string) (AttemptWorkspaceObjectID, error) {
	return parseID[AttemptWorkspaceObjectID](value, "attempt_workspace_object_id")
}

// ParseStarterWorkspaceEntryID validates and converts the shared identifier representation.
func ParseStarterWorkspaceEntryID(value string) (StarterWorkspaceEntryID, error) {
	return parseID[StarterWorkspaceEntryID](value, "starter_workspace_entry_id")
}

// ParseStarterWorkspaceObjectID validates and converts the shared identifier representation.
func ParseStarterWorkspaceObjectID(value string) (StarterWorkspaceObjectID, error) {
	return parseID[StarterWorkspaceObjectID](value, "starter_workspace_object_id")
}

// ParseUserID validates and converts the shared identifier representation.
func ParseUserID(value string) (UserID, error) {
	return parseID[UserID](value, "user_id")
}

// ParseSessionID validates and converts the shared identifier representation.
func ParseSessionID(value string) (SessionID, error) {
	return parseID[SessionID](value, "session_id")
}

// ParseSessionCredentialID validates and converts the shared identifier representation.
func ParseSessionCredentialID(value string) (SessionCredentialID, error) {
	return parseID[SessionCredentialID](value, "session_credential_id")
}

// ParseRoleID validates and converts the shared identifier representation.
func ParseRoleID(value string) (RoleID, error) {
	return parseID[RoleID](value, "role_id")
}

// ParseRoleBindingID validates and converts the shared identifier representation.
func ParseRoleBindingID(value string) (RoleBindingID, error) {
	return parseID[RoleBindingID](value, "role_binding_id")
}

// ParseAffiliationID validates and converts the shared identifier representation.
func ParseAffiliationID(value string) (AffiliationID, error) {
	return parseID[AffiliationID](value, "affiliation_id")
}

// ParseAcademicUnitMemberID validates and converts the shared identifier representation.
func ParseAcademicUnitMemberID(value string) (AcademicUnitMemberID, error) {
	return parseID[AcademicUnitMemberID](value, "academic_unit_member_id")
}

// ParseClassMemberID validates and converts the shared identifier representation.
func ParseClassMemberID(value string) (ClassMemberID, error) {
	return parseID[ClassMemberID](value, "class_member_id")
}

// ParseExternalIdentityID validates and converts the shared identifier representation.
func ParseExternalIdentityID(value string) (ExternalIdentityID, error) {
	return parseID[ExternalIdentityID](value, "external_identity_id")
}

// ParsePasswordCredentialID validates and converts the shared identifier representation.
func ParsePasswordCredentialID(value string) (PasswordCredentialID, error) {
	return parseID[PasswordCredentialID](value, "password_credential_id")
}

// ParsePersonalAccessTokenID validates and converts the shared identifier representation.
func ParsePersonalAccessTokenID(value string) (PersonalAccessTokenID, error) {
	return parseID[PersonalAccessTokenID](value, "personal_access_token_id")
}

// ParseUserTokenID validates and converts the shared identifier representation.
func ParseUserTokenID(value string) (UserTokenID, error) {
	return parseID[UserTokenID](value, "user_token_id")
}

// ParseMFACredentialID validates and converts the shared identifier representation.
func ParseMFACredentialID(value string) (MFACredentialID, error) {
	return parseID[MFACredentialID](value, "mfa_credential_id")
}

// ParseMFARecoveryCodeID validates and converts the shared identifier representation.
func ParseMFARecoveryCodeID(value string) (MFARecoveryCodeID, error) {
	return parseID[MFARecoveryCodeID](value, "mfa_recovery_code_id")
}

// ParseAuditEventID validates and converts the shared identifier representation.
func ParseAuditEventID(value string) (AuditEventID, error) {
	return parseID[AuditEventID](value, "audit_event_id")
}

// ParseExternalLoginStateID validates and converts the shared identifier representation.
func ParseExternalLoginStateID(value string) (ExternalLoginStateID, error) {
	return parseID[ExternalLoginStateID](value, "external_login_state_id")
}

// ParseFileEntryID validates and converts the shared identifier representation.
func ParseFileEntryID(value string) (FileEntryID, error) {
	return parseID[FileEntryID](value, "file_entry_id")
}

// ParseFileRevisionID validates and converts the shared identifier representation.
func ParseFileRevisionID(value string) (FileRevisionID, error) {
	return parseID[FileRevisionID](value, "file_revision_id")
}

// ParseFileRenditionID validates and converts the shared identifier representation.
func ParseFileRenditionID(value string) (FileRenditionID, error) {
	return parseID[FileRenditionID](value, "file_rendition_id")
}

// ParseUploadLeaseID validates and converts the shared identifier representation.
func ParseUploadLeaseID(value string) (UploadLeaseID, error) {
	return parseID[UploadLeaseID](value, "upload_lease_id")
}

// IsZero reports whether the institution is the empty zero value.
func (id InstitutionID) IsZero() bool { return id == "" }

// IsZero reports whether the academic-unit is the empty zero value.
func (id AcademicUnitID) IsZero() bool { return id == "" }

// IsZero reports whether the programme is the empty zero value.
func (id ProgrammeID) IsZero() bool { return id == "" }

// IsZero reports whether the programme-level is the empty zero value.
func (id ProgrammeLevelID) IsZero() bool { return id == "" }

// IsZero reports whether the class is the empty zero value.
func (id ClassID) IsZero() bool { return id == "" }

// IsZero reports whether the academic-period is the empty zero value.
func (id AcademicPeriodID) IsZero() bool { return id == "" }

// IsZero reports whether the exam is the empty zero value.
func (id ExamID) IsZero() bool { return id == "" }

// IsZero reports whether the exam-revision is the empty zero value.
func (id ExamRevisionID) IsZero() bool { return id == "" }

// IsZero reports whether the exam-sitting is the empty zero value.
func (id ExamSittingID) IsZero() bool { return id == "" }

// IsZero reports whether the exam-resource is the empty zero value.
func (id ExamResourceID) IsZero() bool { return id == "" }

// IsZero reports whether the exam-correction-resource-stage is the empty zero value.
func (id ExamCorrectionResourceStageID) IsZero() bool { return id == "" }

// IsZero reports whether the exam-attempt is the empty zero value.
func (id ExamAttemptID) IsZero() bool { return id == "" }

// IsZero reports whether the exam-attempt-workspace is the empty zero value.
func (id ExamAttemptWorkspaceID) IsZero() bool { return id == "" }

// IsZero reports whether the attempt-participation is the empty zero value.
func (id AttemptParticipationID) IsZero() bool { return id == "" }

// IsZero reports whether the attempt-connection is the empty zero value.
func (id AttemptConnectionID) IsZero() bool { return id == "" }

// IsZero reports whether the focus-loss-signal is the empty zero value.
func (id FocusLossSignalID) IsZero() bool { return id == "" }

// IsZero reports whether the integrity-evidence is the empty zero value.
func (id IntegrityEvidenceID) IsZero() bool { return id == "" }

// IsZero reports whether the integrity-flag is the empty zero value.
func (id IntegrityFlagID) IsZero() bool { return id == "" }

// IsZero reports whether the attempt-suspension is the empty zero value.
func (id AttemptSuspensionID) IsZero() bool { return id == "" }

// IsZero reports whether the attempt-workspace-entry is the empty zero value.
func (id AttemptWorkspaceEntryID) IsZero() bool { return id == "" }

// IsZero reports whether the attempt-workspace-object is the empty zero value.
func (id AttemptWorkspaceObjectID) IsZero() bool { return id == "" }

// IsZero reports whether the starter-workspace-entry is the empty zero value.
func (id StarterWorkspaceEntryID) IsZero() bool { return id == "" }

// IsZero reports whether the starter-workspace-object is the empty zero value.
func (id StarterWorkspaceObjectID) IsZero() bool { return id == "" }

// IsZero reports whether the user is the empty zero value.
func (id UserID) IsZero() bool { return id == "" }

// IsZero reports whether the session is the empty zero value.
func (id SessionID) IsZero() bool { return id == "" }

// IsZero reports whether the session-credential is the empty zero value.
func (id SessionCredentialID) IsZero() bool { return id == "" }

// IsZero reports whether the role is the empty zero value.
func (id RoleID) IsZero() bool { return id == "" }

// IsZero reports whether the role-binding is the empty zero value.
func (id RoleBindingID) IsZero() bool { return id == "" }

// IsZero reports whether the affiliation is the empty zero value.
func (id AffiliationID) IsZero() bool { return id == "" }

// IsZero reports whether the academic-unit-member is the empty zero value.
func (id AcademicUnitMemberID) IsZero() bool { return id == "" }

// IsZero reports whether the class-member is the empty zero value.
func (id ClassMemberID) IsZero() bool { return id == "" }

// IsZero reports whether the external-identity is the empty zero value.
func (id ExternalIdentityID) IsZero() bool { return id == "" }

// IsZero reports whether the password-credential is the empty zero value.
func (id PasswordCredentialID) IsZero() bool { return id == "" }

// IsZero reports whether the personal-access-token is the empty zero value.
func (id PersonalAccessTokenID) IsZero() bool { return id == "" }

// IsZero reports whether the user-token is the empty zero value.
func (id UserTokenID) IsZero() bool { return id == "" }

// IsZero reports whether the MFA credential is the empty zero value.
func (id MFACredentialID) IsZero() bool { return id == "" }

// IsZero reports whether the MFA recovery-code is the empty zero value.
func (id MFARecoveryCodeID) IsZero() bool { return id == "" }

// IsZero reports whether the audit-event is the empty zero value.
func (id AuditEventID) IsZero() bool { return id == "" }

// IsZero reports whether the external-login-state is the empty zero value.
func (id ExternalLoginStateID) IsZero() bool { return id == "" }

// IsZero reports whether the file-entry is the empty zero value.
func (id FileEntryID) IsZero() bool { return id == "" }

// IsZero reports whether the file-revision is the empty zero value.
func (id FileRevisionID) IsZero() bool { return id == "" }

// IsZero reports whether the file-rendition is the empty zero value.
func (id FileRenditionID) IsZero() bool { return id == "" }

// IsZero reports whether the upload-lease is the empty zero value.
func (id UploadLeaseID) IsZero() bool { return id == "" }

// IsValid reports whether the institution is a canonical non-zero ID.
func (id InstitutionID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the academic-unit is a canonical non-zero ID.
func (id AcademicUnitID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the programme is a canonical non-zero ID.
func (id ProgrammeID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the programme-level is a canonical non-zero ID.
func (id ProgrammeLevelID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the class is a canonical non-zero ID.
func (id ClassID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the academic-period is a canonical non-zero ID.
func (id AcademicPeriodID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the exam is a canonical non-zero ID.
func (id ExamID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the exam-revision is a canonical non-zero ID.
func (id ExamRevisionID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the exam-sitting is a canonical non-zero ID.
func (id ExamSittingID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the exam-resource is a canonical non-zero ID.
func (id ExamResourceID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the exam-correction-resource-stage is a canonical non-zero ID.
func (id ExamCorrectionResourceStageID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the exam-attempt is a canonical non-zero ID.
func (id ExamAttemptID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the exam-attempt-workspace is a canonical non-zero ID.
func (id ExamAttemptWorkspaceID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the attempt-participation is a canonical non-zero ID.
func (id AttemptParticipationID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the attempt-connection is a canonical non-zero ID.
func (id AttemptConnectionID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the focus-loss-signal is a canonical non-zero ID.
func (id FocusLossSignalID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the integrity-evidence is a canonical non-zero ID.
func (id IntegrityEvidenceID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the integrity-flag is a canonical non-zero ID.
func (id IntegrityFlagID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the attempt-suspension is a canonical non-zero ID.
func (id AttemptSuspensionID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the attempt-workspace-entry is a canonical non-zero ID.
func (id AttemptWorkspaceEntryID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the attempt-workspace-object is a canonical non-zero ID.
func (id AttemptWorkspaceObjectID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the starter-workspace-entry is a canonical non-zero ID.
func (id StarterWorkspaceEntryID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the starter-workspace-object is a canonical non-zero ID.
func (id StarterWorkspaceObjectID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the user is a canonical non-zero ID.
func (id UserID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the session is a canonical non-zero ID.
func (id SessionID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the session-credential is a canonical non-zero ID.
func (id SessionCredentialID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the role is a canonical non-zero ID.
func (id RoleID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the role-binding is a canonical non-zero ID.
func (id RoleBindingID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the affiliation is a canonical non-zero ID.
func (id AffiliationID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the academic-unit-member is a canonical non-zero ID.
func (id AcademicUnitMemberID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the class-member is a canonical non-zero ID.
func (id ClassMemberID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the external-identity is a canonical non-zero ID.
func (id ExternalIdentityID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the password-credential is a canonical non-zero ID.
func (id PasswordCredentialID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the personal-access-token is a canonical non-zero ID.
func (id PersonalAccessTokenID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the user-token is a canonical non-zero ID.
func (id UserTokenID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the MFA credential is a canonical non-zero ID.
func (id MFACredentialID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the MFA recovery-code is a canonical non-zero ID.
func (id MFARecoveryCodeID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the audit-event is a canonical non-zero ID.
func (id AuditEventID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the external-login-state is a canonical non-zero ID.
func (id ExternalLoginStateID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the file-entry is a canonical non-zero ID.
func (id FileEntryID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the file-revision is a canonical non-zero ID.
func (id FileRevisionID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the file-rendition is a canonical non-zero ID.
func (id FileRenditionID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the upload-lease is a canonical non-zero ID.
func (id UploadLeaseID) IsValid() bool { return IsValidId(string(id)) }

// String returns the institution wire/database representation.
func (id InstitutionID) String() string { return string(id) }

// String returns the academic-unit wire/database representation.
func (id AcademicUnitID) String() string { return string(id) }

// String returns the programme wire/database representation.
func (id ProgrammeID) String() string { return string(id) }

// String returns the programme-level wire/database representation.
func (id ProgrammeLevelID) String() string { return string(id) }

// String returns the class wire/database representation.
func (id ClassID) String() string { return string(id) }

// String returns the academic-period wire/database representation.
func (id AcademicPeriodID) String() string { return string(id) }

// String returns the exam wire/database representation.
func (id ExamID) String() string { return string(id) }

// String returns the exam-revision wire/database representation.
func (id ExamRevisionID) String() string { return string(id) }

// String returns the exam-sitting wire/database representation.
func (id ExamSittingID) String() string { return string(id) }

// String returns the exam-resource wire/database representation.
func (id ExamResourceID) String() string { return string(id) }

// String returns the exam-correction-resource-stage wire/database representation.
func (id ExamCorrectionResourceStageID) String() string { return string(id) }

// String returns the exam-attempt wire/database representation.
func (id ExamAttemptID) String() string { return string(id) }

// String returns the exam-attempt-workspace wire/database representation.
func (id ExamAttemptWorkspaceID) String() string { return string(id) }

// String returns the attempt-participation wire/database representation.
func (id AttemptParticipationID) String() string { return string(id) }

// String returns the attempt-connection wire/database representation.
func (id AttemptConnectionID) String() string { return string(id) }

// String returns the focus-loss-signal wire/database representation.
func (id FocusLossSignalID) String() string { return string(id) }

// String returns the integrity-evidence wire/database representation.
func (id IntegrityEvidenceID) String() string { return string(id) }

// String returns the integrity-flag wire/database representation.
func (id IntegrityFlagID) String() string { return string(id) }

// String returns the attempt-suspension wire/database representation.
func (id AttemptSuspensionID) String() string { return string(id) }

// String returns the attempt-workspace-entry wire/database representation.
func (id AttemptWorkspaceEntryID) String() string { return string(id) }

// String returns the attempt-workspace-object wire/database representation.
func (id AttemptWorkspaceObjectID) String() string { return string(id) }

// String returns the starter-workspace-entry wire/database representation.
func (id StarterWorkspaceEntryID) String() string { return string(id) }

// String returns the starter-workspace-object wire/database representation.
func (id StarterWorkspaceObjectID) String() string { return string(id) }

// String returns the user wire/database representation.
func (id UserID) String() string { return string(id) }

// String returns the session wire/database representation.
func (id SessionID) String() string { return string(id) }

// String returns the session-credential wire/database representation.
func (id SessionCredentialID) String() string { return string(id) }

// String returns the role wire/database representation.
func (id RoleID) String() string { return string(id) }

// String returns the role-binding wire/database representation.
func (id RoleBindingID) String() string { return string(id) }

// String returns the affiliation wire/database representation.
func (id AffiliationID) String() string { return string(id) }

// String returns the academic-unit-member wire/database representation.
func (id AcademicUnitMemberID) String() string { return string(id) }

// String returns the class-member wire/database representation.
func (id ClassMemberID) String() string { return string(id) }

// String returns the external-identity wire/database representation.
func (id ExternalIdentityID) String() string { return string(id) }

// String returns the password-credential wire/database representation.
func (id PasswordCredentialID) String() string { return string(id) }

// String returns the personal-access-token wire/database representation.
func (id PersonalAccessTokenID) String() string { return string(id) }

// String returns the user-token wire/database representation.
func (id UserTokenID) String() string { return string(id) }

// String returns the MFA credential wire/database representation.
func (id MFACredentialID) String() string { return string(id) }

// String returns the MFA recovery-code wire/database representation.
func (id MFARecoveryCodeID) String() string { return string(id) }

// String returns the audit-event wire/database representation.
func (id AuditEventID) String() string { return string(id) }

// String returns the external-login-state wire/database representation.
func (id ExternalLoginStateID) String() string { return string(id) }

// String returns the file-entry wire/database representation.
func (id FileEntryID) String() string { return string(id) }

// String returns the file-revision wire/database representation.
func (id FileRevisionID) String() string { return string(id) }

// String returns the file-rendition wire/database representation.
func (id FileRenditionID) String() string { return string(id) }

// String returns the upload-lease wire/database representation.
func (id UploadLeaseID) String() string { return string(id) }

// MarshalText encodes the institution as its canonical string.
func (id InstitutionID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the academic-unit as its canonical string.
func (id AcademicUnitID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the programme as its canonical string.
func (id ProgrammeID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the programme-level as its canonical string.
func (id ProgrammeLevelID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the class as its canonical string.
func (id ClassID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the academic-period as its canonical string.
func (id AcademicPeriodID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the exam as its canonical string.
func (id ExamID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the exam-revision as its canonical string.
func (id ExamRevisionID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the exam-sitting as its canonical string.
func (id ExamSittingID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the exam-resource as its canonical string.
func (id ExamResourceID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the exam-correction-resource-stage as its canonical string.
func (id ExamCorrectionResourceStageID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the exam-attempt as its canonical string.
func (id ExamAttemptID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the exam-attempt-workspace as its canonical string.
func (id ExamAttemptWorkspaceID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the attempt-participation as its canonical string.
func (id AttemptParticipationID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the attempt-connection as its canonical string.
func (id AttemptConnectionID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the focus-loss-signal as its canonical string.
func (id FocusLossSignalID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the integrity-evidence as its canonical string.
func (id IntegrityEvidenceID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the integrity-flag as its canonical string.
func (id IntegrityFlagID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the attempt-suspension as its canonical string.
func (id AttemptSuspensionID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the attempt-workspace-entry as its canonical string.
func (id AttemptWorkspaceEntryID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the attempt-workspace-object as its canonical string.
func (id AttemptWorkspaceObjectID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the starter-workspace-entry as its canonical string.
func (id StarterWorkspaceEntryID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the starter-workspace-object as its canonical string.
func (id StarterWorkspaceObjectID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the user as its canonical string.
func (id UserID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the session as its canonical string.
func (id SessionID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the session-credential as its canonical string.
func (id SessionCredentialID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the role as its canonical string.
func (id RoleID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the role-binding as its canonical string.
func (id RoleBindingID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the affiliation as its canonical string.
func (id AffiliationID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the academic-unit-member as its canonical string.
func (id AcademicUnitMemberID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the class-member as its canonical string.
func (id ClassMemberID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the external-identity as its canonical string.
func (id ExternalIdentityID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the password-credential as its canonical string.
func (id PasswordCredentialID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the personal-access-token as its canonical string.
func (id PersonalAccessTokenID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the user-token as its canonical string.
func (id UserTokenID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the MFA credential as its canonical string.
func (id MFACredentialID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the MFA recovery-code as its canonical string.
func (id MFARecoveryCodeID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the audit-event as its canonical string.
func (id AuditEventID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the external-login-state as its canonical string.
func (id ExternalLoginStateID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the file-entry as its canonical string.
func (id FileEntryID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the file-revision as its canonical string.
func (id FileRevisionID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the file-rendition as its canonical string.
func (id FileRenditionID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the upload-lease as its canonical string.
func (id UploadLeaseID) MarshalText() ([]byte, error) { return marshalID(id) }

// UnmarshalText decodes and validates the institution when non-empty.
func (id *InstitutionID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseInstitutionID)
}

// UnmarshalText decodes and validates the academic-unit when non-empty.
func (id *AcademicUnitID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseAcademicUnitID)
}

// UnmarshalText decodes and validates the programme when non-empty.
func (id *ProgrammeID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseProgrammeID)
}

// UnmarshalText decodes and validates the programme-level when non-empty.
func (id *ProgrammeLevelID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseProgrammeLevelID)
}

// UnmarshalText decodes and validates the class when non-empty.
func (id *ClassID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseClassID)
}

// UnmarshalText decodes and validates the academic-period when non-empty.
func (id *AcademicPeriodID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseAcademicPeriodID)
}

// UnmarshalText decodes and validates the exam when non-empty.
func (id *ExamID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseExamID)
}

// UnmarshalText decodes and validates the exam-revision when non-empty.
func (id *ExamRevisionID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseExamRevisionID)
}

// UnmarshalText decodes and validates the exam-sitting when non-empty.
func (id *ExamSittingID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseExamSittingID)
}

// UnmarshalText decodes and validates the exam-resource when non-empty.
func (id *ExamResourceID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseExamResourceID)
}

// UnmarshalText decodes and validates the exam-correction-resource-stage when non-empty.
func (id *ExamCorrectionResourceStageID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseExamCorrectionResourceStageID)
}

// UnmarshalText decodes and validates the exam-attempt when non-empty.
func (id *ExamAttemptID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseExamAttemptID)
}

// UnmarshalText decodes and validates the exam-attempt-workspace when non-empty.
func (id *ExamAttemptWorkspaceID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseExamAttemptWorkspaceID)
}

// UnmarshalText decodes and validates the attempt-participation when non-empty.
func (id *AttemptParticipationID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseAttemptParticipationID)
}

// UnmarshalText decodes and validates the attempt-connection when non-empty.
func (id *AttemptConnectionID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseAttemptConnectionID)
}

// UnmarshalText decodes and validates the focus-loss-signal when non-empty.
func (id *FocusLossSignalID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseFocusLossSignalID)
}

// UnmarshalText decodes and validates the integrity-evidence when non-empty.
func (id *IntegrityEvidenceID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseIntegrityEvidenceID)
}

// UnmarshalText decodes and validates the integrity-flag when non-empty.
func (id *IntegrityFlagID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseIntegrityFlagID)
}

// UnmarshalText decodes and validates the attempt-suspension when non-empty.
func (id *AttemptSuspensionID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseAttemptSuspensionID)
}

// UnmarshalText decodes and validates the attempt-workspace-entry when non-empty.
func (id *AttemptWorkspaceEntryID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseAttemptWorkspaceEntryID)
}

// UnmarshalText decodes and validates the attempt-workspace-object when non-empty.
func (id *AttemptWorkspaceObjectID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseAttemptWorkspaceObjectID)
}

// UnmarshalText decodes and validates the starter-workspace-entry when non-empty.
func (id *StarterWorkspaceEntryID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseStarterWorkspaceEntryID)
}

// UnmarshalText decodes and validates the starter-workspace-object when non-empty.
func (id *StarterWorkspaceObjectID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseStarterWorkspaceObjectID)
}

// UnmarshalText decodes and validates the user when non-empty.
func (id *UserID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseUserID)
}

// UnmarshalText decodes and validates the session when non-empty.
func (id *SessionID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseSessionID)
}

// UnmarshalText decodes and validates the session-credential when non-empty.
func (id *SessionCredentialID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseSessionCredentialID)
}

// UnmarshalText decodes and validates the role when non-empty.
func (id *RoleID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseRoleID)
}

// UnmarshalText decodes and validates the role-binding when non-empty.
func (id *RoleBindingID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseRoleBindingID)
}

// UnmarshalText decodes and validates the affiliation when non-empty.
func (id *AffiliationID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseAffiliationID)
}

// UnmarshalText decodes and validates the academic-unit-member when non-empty.
func (id *AcademicUnitMemberID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseAcademicUnitMemberID)
}

// UnmarshalText decodes and validates the class-member when non-empty.
func (id *ClassMemberID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseClassMemberID)
}

// UnmarshalText decodes and validates the external-identity when non-empty.
func (id *ExternalIdentityID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseExternalIdentityID)
}

// UnmarshalText decodes and validates the password-credential when non-empty.
func (id *PasswordCredentialID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParsePasswordCredentialID)
}

// UnmarshalText decodes and validates the personal-access-token when non-empty.
func (id *PersonalAccessTokenID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParsePersonalAccessTokenID)
}

// UnmarshalText decodes and validates the user-token when non-empty.
func (id *UserTokenID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseUserTokenID)
}

// UnmarshalText decodes and validates the MFA credential when non-empty.
func (id *MFACredentialID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseMFACredentialID)
}

// UnmarshalText decodes and validates the MFA recovery-code when non-empty.
func (id *MFARecoveryCodeID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseMFARecoveryCodeID)
}

// UnmarshalText decodes and validates the audit-event when non-empty.
func (id *AuditEventID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseAuditEventID)
}

// UnmarshalText decodes and validates the external-login-state when non-empty.
func (id *ExternalLoginStateID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseExternalLoginStateID)
}

// UnmarshalText decodes and validates the file-entry when non-empty.
func (id *FileEntryID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseFileEntryID)
}

// UnmarshalText decodes and validates the file-revision when non-empty.
func (id *FileRevisionID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseFileRevisionID)
}

// UnmarshalText decodes and validates the file-rendition when non-empty.
func (id *FileRenditionID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseFileRenditionID)
}

// UnmarshalText decodes and validates the upload-lease when non-empty.
func (id *UploadLeaseID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseUploadLeaseID)
}

// MarshalJSON encodes the institution as a JSON string.
func (id InstitutionID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the academic-unit as a JSON string.
func (id AcademicUnitID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the programme as a JSON string.
func (id ProgrammeID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the programme-level as a JSON string.
func (id ProgrammeLevelID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the class as a JSON string.
func (id ClassID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the academic-period as a JSON string.
func (id AcademicPeriodID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the exam as a JSON string.
func (id ExamID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the exam-revision as a JSON string.
func (id ExamRevisionID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the exam-sitting as a JSON string.
func (id ExamSittingID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the exam-resource as a JSON string.
func (id ExamResourceID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the exam-correction-resource-stage as a JSON string.
func (id ExamCorrectionResourceStageID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the exam-attempt as a JSON string.
func (id ExamAttemptID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the exam-attempt-workspace as a JSON string.
func (id ExamAttemptWorkspaceID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the attempt-participation as a JSON string.
func (id AttemptParticipationID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the attempt-connection as a JSON string.
func (id AttemptConnectionID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the focus-loss-signal as a JSON string.
func (id FocusLossSignalID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the integrity-evidence as a JSON string.
func (id IntegrityEvidenceID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the integrity-flag as a JSON string.
func (id IntegrityFlagID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the attempt-suspension as a JSON string.
func (id AttemptSuspensionID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the attempt-workspace-entry as a JSON string.
func (id AttemptWorkspaceEntryID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the attempt-workspace-object as a JSON string.
func (id AttemptWorkspaceObjectID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the starter-workspace-entry as a JSON string.
func (id StarterWorkspaceEntryID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the starter-workspace-object as a JSON string.
func (id StarterWorkspaceObjectID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the user as a JSON string.
func (id UserID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the session as a JSON string.
func (id SessionID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the session-credential as a JSON string.
func (id SessionCredentialID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the role as a JSON string.
func (id RoleID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the role-binding as a JSON string.
func (id RoleBindingID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the affiliation as a JSON string.
func (id AffiliationID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the academic-unit-member as a JSON string.
func (id AcademicUnitMemberID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the class-member as a JSON string.
func (id ClassMemberID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the external-identity as a JSON string.
func (id ExternalIdentityID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the password-credential as a JSON string.
func (id PasswordCredentialID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the personal-access-token as a JSON string.
func (id PersonalAccessTokenID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the user-token as a JSON string.
func (id UserTokenID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the MFA credential as a JSON string.
func (id MFACredentialID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the MFA recovery-code as a JSON string.
func (id MFARecoveryCodeID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the audit-event as a JSON string.
func (id AuditEventID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the external-login-state as a JSON string.
func (id ExternalLoginStateID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the file-entry as a JSON string.
func (id FileEntryID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the file-revision as a JSON string.
func (id FileRevisionID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the file-rendition as a JSON string.
func (id FileRenditionID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the upload-lease as a JSON string.
func (id UploadLeaseID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// UnmarshalJSON decodes a JSON string into the institution.
func (id *InstitutionID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseInstitutionID)
}

// UnmarshalJSON decodes a JSON string into the academic-unit.
func (id *AcademicUnitID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseAcademicUnitID)
}

// UnmarshalJSON decodes a JSON string into the programme.
func (id *ProgrammeID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseProgrammeID)
}

// UnmarshalJSON decodes a JSON string into the programme-level.
func (id *ProgrammeLevelID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseProgrammeLevelID)
}

// UnmarshalJSON decodes a JSON string into the class.
func (id *ClassID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseClassID)
}

// UnmarshalJSON decodes a JSON string into the academic-period.
func (id *AcademicPeriodID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseAcademicPeriodID)
}

// UnmarshalJSON decodes a JSON string into the exam.
func (id *ExamID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseExamID)
}

// UnmarshalJSON decodes a JSON string into the exam-revision.
func (id *ExamRevisionID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseExamRevisionID)
}

// UnmarshalJSON decodes a JSON string into the exam-sitting.
func (id *ExamSittingID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseExamSittingID)
}

// UnmarshalJSON decodes a JSON string into the exam-resource.
func (id *ExamResourceID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseExamResourceID)
}

// UnmarshalJSON decodes a JSON string into the exam-correction-resource-stage.
func (id *ExamCorrectionResourceStageID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseExamCorrectionResourceStageID)
}

// UnmarshalJSON decodes a JSON string into the exam-attempt.
func (id *ExamAttemptID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseExamAttemptID)
}

// UnmarshalJSON decodes a JSON string into the exam-attempt-workspace.
func (id *ExamAttemptWorkspaceID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseExamAttemptWorkspaceID)
}

// UnmarshalJSON decodes a JSON string into the attempt-participation.
func (id *AttemptParticipationID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseAttemptParticipationID)
}

// UnmarshalJSON decodes a JSON string into the attempt-connection.
func (id *AttemptConnectionID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseAttemptConnectionID)
}

// UnmarshalJSON decodes a JSON string into the focus-loss-signal.
func (id *FocusLossSignalID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseFocusLossSignalID)
}

// UnmarshalJSON decodes a JSON string into the integrity-evidence.
func (id *IntegrityEvidenceID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseIntegrityEvidenceID)
}

// UnmarshalJSON decodes a JSON string into the integrity-flag.
func (id *IntegrityFlagID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseIntegrityFlagID)
}

// UnmarshalJSON decodes a JSON string into the attempt-suspension.
func (id *AttemptSuspensionID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseAttemptSuspensionID)
}

// UnmarshalJSON decodes a JSON string into the attempt-workspace-entry.
func (id *AttemptWorkspaceEntryID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseAttemptWorkspaceEntryID)
}

// UnmarshalJSON decodes a JSON string into the attempt-workspace-object.
func (id *AttemptWorkspaceObjectID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseAttemptWorkspaceObjectID)
}

// UnmarshalJSON decodes a JSON string into the starter-workspace-entry.
func (id *StarterWorkspaceEntryID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseStarterWorkspaceEntryID)
}

// UnmarshalJSON decodes a JSON string into the starter-workspace-object.
func (id *StarterWorkspaceObjectID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseStarterWorkspaceObjectID)
}

// UnmarshalJSON decodes a JSON string into the user.
func (id *UserID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseUserID)
}

// UnmarshalJSON decodes a JSON string into the session.
func (id *SessionID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseSessionID)
}

// UnmarshalJSON decodes a JSON string into the session-credential.
func (id *SessionCredentialID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseSessionCredentialID)
}

// UnmarshalJSON decodes a JSON string into the role.
func (id *RoleID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseRoleID)
}

// UnmarshalJSON decodes a JSON string into the role-binding.
func (id *RoleBindingID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseRoleBindingID)
}

// UnmarshalJSON decodes a JSON string into the affiliation.
func (id *AffiliationID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseAffiliationID)
}

// UnmarshalJSON decodes a JSON string into the academic-unit-member.
func (id *AcademicUnitMemberID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseAcademicUnitMemberID)
}

// UnmarshalJSON decodes a JSON string into the class-member.
func (id *ClassMemberID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseClassMemberID)
}

// UnmarshalJSON decodes a JSON string into the external-identity.
func (id *ExternalIdentityID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseExternalIdentityID)
}

// UnmarshalJSON decodes a JSON string into the password-credential.
func (id *PasswordCredentialID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParsePasswordCredentialID)
}

// UnmarshalJSON decodes a JSON string into the personal-access-token.
func (id *PersonalAccessTokenID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParsePersonalAccessTokenID)
}

// UnmarshalJSON decodes a JSON string into the user-token.
func (id *UserTokenID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseUserTokenID)
}

// UnmarshalJSON decodes a JSON string into the MFA credential.
func (id *MFACredentialID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseMFACredentialID)
}

// UnmarshalJSON decodes a JSON string into the MFA recovery-code.
func (id *MFARecoveryCodeID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseMFARecoveryCodeID)
}

// UnmarshalJSON decodes a JSON string into the audit-event.
func (id *AuditEventID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseAuditEventID)
}

// UnmarshalJSON decodes a JSON string into the external-login-state.
func (id *ExternalLoginStateID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseExternalLoginStateID)
}

// UnmarshalJSON decodes a JSON string into the file-entry.
func (id *FileEntryID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseFileEntryID)
}

// UnmarshalJSON decodes a JSON string into the file-revision.
func (id *FileRevisionID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseFileRevisionID)
}

// UnmarshalJSON decodes a JSON string into the file-rendition.
func (id *FileRenditionID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseFileRenditionID)
}

// UnmarshalJSON decodes a JSON string into the upload-lease.
func (id *UploadLeaseID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseUploadLeaseID)
}
