// Code generated by go generate; DO NOT EDIT.

// Copyright 2026 SudoSylabs
// SPDX-License-Identifier: AGPL-3.0-only

package model

// NewInstitutionID returns a freshly generated institution identifier.
func NewInstitutionID() InstitutionID { return InstitutionID(NewId()) }

// NewAcademicUnitID returns a freshly generated academic-unit identifier.
func NewAcademicUnitID() AcademicUnitID { return AcademicUnitID(NewId()) }

// NewProgrammeID returns a freshly generated programme identifier.
func NewProgrammeID() ProgrammeID { return ProgrammeID(NewId()) }

// NewProgrammeLevelID returns a freshly generated programme-level identifier.
func NewProgrammeLevelID() ProgrammeLevelID { return ProgrammeLevelID(NewId()) }

// NewClassID returns a freshly generated class identifier.
func NewClassID() ClassID { return ClassID(NewId()) }

// NewAcademicPeriodID returns a freshly generated academic-period identifier.
func NewAcademicPeriodID() AcademicPeriodID { return AcademicPeriodID(NewId()) }

// NewExamID returns a freshly generated exam identifier.
func NewExamID() ExamID { return ExamID(NewId()) }

// NewExamRevisionID returns a freshly generated exam-revision identifier.
func NewExamRevisionID() ExamRevisionID { return ExamRevisionID(NewId()) }

// NewUserID returns a freshly generated user identifier.
func NewUserID() UserID { return UserID(NewId()) }

// NewSessionID returns a freshly generated session identifier.
func NewSessionID() SessionID { return SessionID(NewId()) }

// NewSessionCredentialID returns a freshly generated session-credential identifier.
func NewSessionCredentialID() SessionCredentialID { return SessionCredentialID(NewId()) }

// NewRoleID returns a freshly generated role identifier.
func NewRoleID() RoleID { return RoleID(NewId()) }

// NewRoleBindingID returns a freshly generated role-binding identifier.
func NewRoleBindingID() RoleBindingID { return RoleBindingID(NewId()) }

// NewAffiliationID returns a freshly generated affiliation identifier.
func NewAffiliationID() AffiliationID { return AffiliationID(NewId()) }

// NewAcademicUnitMemberID returns a freshly generated academic-unit-member identifier.
func NewAcademicUnitMemberID() AcademicUnitMemberID { return AcademicUnitMemberID(NewId()) }

// NewClassMemberID returns a freshly generated class-member identifier.
func NewClassMemberID() ClassMemberID { return ClassMemberID(NewId()) }

// NewExternalIdentityID returns a freshly generated external-identity identifier.
func NewExternalIdentityID() ExternalIdentityID { return ExternalIdentityID(NewId()) }

// NewPasswordCredentialID returns a freshly generated password-credential identifier.
func NewPasswordCredentialID() PasswordCredentialID { return PasswordCredentialID(NewId()) }

// NewPersonalAccessTokenID returns a freshly generated personal-access-token identifier.
func NewPersonalAccessTokenID() PersonalAccessTokenID { return PersonalAccessTokenID(NewId()) }

// NewUserTokenID returns a freshly generated user-token identifier.
func NewUserTokenID() UserTokenID { return UserTokenID(NewId()) }

// NewMFACredentialID returns a freshly generated MFA credential identifier.
func NewMFACredentialID() MFACredentialID { return MFACredentialID(NewId()) }

// NewMFARecoveryCodeID returns a freshly generated MFA recovery-code identifier.
func NewMFARecoveryCodeID() MFARecoveryCodeID { return MFARecoveryCodeID(NewId()) }

// NewAuditEventID returns a freshly generated audit-event identifier.
func NewAuditEventID() AuditEventID { return AuditEventID(NewId()) }

// NewExternalLoginStateID returns a freshly generated external-login-state identifier.
func NewExternalLoginStateID() ExternalLoginStateID { return ExternalLoginStateID(NewId()) }

// NewFileEntryID returns a freshly generated file-entry identifier.
func NewFileEntryID() FileEntryID { return FileEntryID(NewId()) }

// NewFileRevisionID returns a freshly generated file-revision identifier.
func NewFileRevisionID() FileRevisionID { return FileRevisionID(NewId()) }

// NewFileRenditionID returns a freshly generated file-rendition identifier.
func NewFileRenditionID() FileRenditionID { return FileRenditionID(NewId()) }

// NewUploadLeaseID returns a freshly generated upload-lease identifier.
func NewUploadLeaseID() UploadLeaseID { return UploadLeaseID(NewId()) }

// ParseInstitutionID validates and converts the shared identifier representation.
func ParseInstitutionID(value string) (InstitutionID, error) {
	return parseID[InstitutionID](value, "institution_id")
}

// ParseAcademicUnitID validates and converts the shared identifier representation.
func ParseAcademicUnitID(value string) (AcademicUnitID, error) {
	return parseID[AcademicUnitID](value, "academic_unit_id")
}

// ParseProgrammeID validates and converts the shared identifier representation.
func ParseProgrammeID(value string) (ProgrammeID, error) {
	return parseID[ProgrammeID](value, "programme_id")
}

// ParseProgrammeLevelID validates and converts the shared identifier representation.
func ParseProgrammeLevelID(value string) (ProgrammeLevelID, error) {
	return parseID[ProgrammeLevelID](value, "programme_level_id")
}

// ParseClassID validates and converts the shared identifier representation.
func ParseClassID(value string) (ClassID, error) {
	return parseID[ClassID](value, "class_id")
}

// ParseAcademicPeriodID validates and converts the shared identifier representation.
func ParseAcademicPeriodID(value string) (AcademicPeriodID, error) {
	return parseID[AcademicPeriodID](value, "academic_period_id")
}

// ParseExamID validates and converts the shared identifier representation.
func ParseExamID(value string) (ExamID, error) {
	return parseID[ExamID](value, "exam_id")
}

// ParseExamRevisionID validates and converts the shared identifier representation.
func ParseExamRevisionID(value string) (ExamRevisionID, error) {
	return parseID[ExamRevisionID](value, "exam_revision_id")
}

// ParseUserID validates and converts the shared identifier representation.
func ParseUserID(value string) (UserID, error) {
	return parseID[UserID](value, "user_id")
}

// ParseSessionID validates and converts the shared identifier representation.
func ParseSessionID(value string) (SessionID, error) {
	return parseID[SessionID](value, "session_id")
}

// ParseSessionCredentialID validates and converts the shared identifier representation.
func ParseSessionCredentialID(value string) (SessionCredentialID, error) {
	return parseID[SessionCredentialID](value, "session_credential_id")
}

// ParseRoleID validates and converts the shared identifier representation.
func ParseRoleID(value string) (RoleID, error) {
	return parseID[RoleID](value, "role_id")
}

// ParseRoleBindingID validates and converts the shared identifier representation.
func ParseRoleBindingID(value string) (RoleBindingID, error) {
	return parseID[RoleBindingID](value, "role_binding_id")
}

// ParseAffiliationID validates and converts the shared identifier representation.
func ParseAffiliationID(value string) (AffiliationID, error) {
	return parseID[AffiliationID](value, "affiliation_id")
}

// ParseAcademicUnitMemberID validates and converts the shared identifier representation.
func ParseAcademicUnitMemberID(value string) (AcademicUnitMemberID, error) {
	return parseID[AcademicUnitMemberID](value, "academic_unit_member_id")
}

// ParseClassMemberID validates and converts the shared identifier representation.
func ParseClassMemberID(value string) (ClassMemberID, error) {
	return parseID[ClassMemberID](value, "class_member_id")
}

// ParseExternalIdentityID validates and converts the shared identifier representation.
func ParseExternalIdentityID(value string) (ExternalIdentityID, error) {
	return parseID[ExternalIdentityID](value, "external_identity_id")
}

// ParsePasswordCredentialID validates and converts the shared identifier representation.
func ParsePasswordCredentialID(value string) (PasswordCredentialID, error) {
	return parseID[PasswordCredentialID](value, "password_credential_id")
}

// ParsePersonalAccessTokenID validates and converts the shared identifier representation.
func ParsePersonalAccessTokenID(value string) (PersonalAccessTokenID, error) {
	return parseID[PersonalAccessTokenID](value, "personal_access_token_id")
}

// ParseUserTokenID validates and converts the shared identifier representation.
func ParseUserTokenID(value string) (UserTokenID, error) {
	return parseID[UserTokenID](value, "user_token_id")
}

// ParseMFACredentialID validates and converts the shared identifier representation.
func ParseMFACredentialID(value string) (MFACredentialID, error) {
	return parseID[MFACredentialID](value, "mfa_credential_id")
}

// ParseMFARecoveryCodeID validates and converts the shared identifier representation.
func ParseMFARecoveryCodeID(value string) (MFARecoveryCodeID, error) {
	return parseID[MFARecoveryCodeID](value, "mfa_recovery_code_id")
}

// ParseAuditEventID validates and converts the shared identifier representation.
func ParseAuditEventID(value string) (AuditEventID, error) {
	return parseID[AuditEventID](value, "audit_event_id")
}

// ParseExternalLoginStateID validates and converts the shared identifier representation.
func ParseExternalLoginStateID(value string) (ExternalLoginStateID, error) {
	return parseID[ExternalLoginStateID](value, "external_login_state_id")
}

// ParseFileEntryID validates and converts the shared identifier representation.
func ParseFileEntryID(value string) (FileEntryID, error) {
	return parseID[FileEntryID](value, "file_entry_id")
}

// ParseFileRevisionID validates and converts the shared identifier representation.
func ParseFileRevisionID(value string) (FileRevisionID, error) {
	return parseID[FileRevisionID](value, "file_revision_id")
}

// ParseFileRenditionID validates and converts the shared identifier representation.
func ParseFileRenditionID(value string) (FileRenditionID, error) {
	return parseID[FileRenditionID](value, "file_rendition_id")
}

// ParseUploadLeaseID validates and converts the shared identifier representation.
func ParseUploadLeaseID(value string) (UploadLeaseID, error) {
	return parseID[UploadLeaseID](value, "upload_lease_id")
}

// IsZero reports whether the institution is the empty zero value.
func (id InstitutionID) IsZero() bool { return id == "" }

// IsZero reports whether the academic-unit is the empty zero value.
func (id AcademicUnitID) IsZero() bool { return id == "" }

// IsZero reports whether the programme is the empty zero value.
func (id ProgrammeID) IsZero() bool { return id == "" }

// IsZero reports whether the programme-level is the empty zero value.
func (id ProgrammeLevelID) IsZero() bool { return id == "" }

// IsZero reports whether the class is the empty zero value.
func (id ClassID) IsZero() bool { return id == "" }

// IsZero reports whether the academic-period is the empty zero value.
func (id AcademicPeriodID) IsZero() bool { return id == "" }

// IsZero reports whether the exam is the empty zero value.
func (id ExamID) IsZero() bool { return id == "" }

// IsZero reports whether the exam-revision is the empty zero value.
func (id ExamRevisionID) IsZero() bool { return id == "" }

// IsZero reports whether the user is the empty zero value.
func (id UserID) IsZero() bool { return id == "" }

// IsZero reports whether the session is the empty zero value.
func (id SessionID) IsZero() bool { return id == "" }

// IsZero reports whether the session-credential is the empty zero value.
func (id SessionCredentialID) IsZero() bool { return id == "" }

// IsZero reports whether the role is the empty zero value.
func (id RoleID) IsZero() bool { return id == "" }

// IsZero reports whether the role-binding is the empty zero value.
func (id RoleBindingID) IsZero() bool { return id == "" }

// IsZero reports whether the affiliation is the empty zero value.
func (id AffiliationID) IsZero() bool { return id == "" }

// IsZero reports whether the academic-unit-member is the empty zero value.
func (id AcademicUnitMemberID) IsZero() bool { return id == "" }

// IsZero reports whether the class-member is the empty zero value.
func (id ClassMemberID) IsZero() bool { return id == "" }

// IsZero reports whether the external-identity is the empty zero value.
func (id ExternalIdentityID) IsZero() bool { return id == "" }

// IsZero reports whether the password-credential is the empty zero value.
func (id PasswordCredentialID) IsZero() bool { return id == "" }

// IsZero reports whether the personal-access-token is the empty zero value.
func (id PersonalAccessTokenID) IsZero() bool { return id == "" }

// IsZero reports whether the user-token is the empty zero value.
func (id UserTokenID) IsZero() bool { return id == "" }

// IsZero reports whether the MFA credential is the empty zero value.
func (id MFACredentialID) IsZero() bool { return id == "" }

// IsZero reports whether the MFA recovery-code is the empty zero value.
func (id MFARecoveryCodeID) IsZero() bool { return id == "" }

// IsZero reports whether the audit-event is the empty zero value.
func (id AuditEventID) IsZero() bool { return id == "" }

// IsZero reports whether the external-login-state is the empty zero value.
func (id ExternalLoginStateID) IsZero() bool { return id == "" }

// IsZero reports whether the file-entry is the empty zero value.
func (id FileEntryID) IsZero() bool { return id == "" }

// IsZero reports whether the file-revision is the empty zero value.
func (id FileRevisionID) IsZero() bool { return id == "" }

// IsZero reports whether the file-rendition is the empty zero value.
func (id FileRenditionID) IsZero() bool { return id == "" }

// IsZero reports whether the upload-lease is the empty zero value.
func (id UploadLeaseID) IsZero() bool { return id == "" }

// IsValid reports whether the institution is a canonical non-zero ID.
func (id InstitutionID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the academic-unit is a canonical non-zero ID.
func (id AcademicUnitID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the programme is a canonical non-zero ID.
func (id ProgrammeID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the programme-level is a canonical non-zero ID.
func (id ProgrammeLevelID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the class is a canonical non-zero ID.
func (id ClassID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the academic-period is a canonical non-zero ID.
func (id AcademicPeriodID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the exam is a canonical non-zero ID.
func (id ExamID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the exam-revision is a canonical non-zero ID.
func (id ExamRevisionID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the user is a canonical non-zero ID.
func (id UserID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the session is a canonical non-zero ID.
func (id SessionID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the session-credential is a canonical non-zero ID.
func (id SessionCredentialID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the role is a canonical non-zero ID.
func (id RoleID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the role-binding is a canonical non-zero ID.
func (id RoleBindingID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the affiliation is a canonical non-zero ID.
func (id AffiliationID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the academic-unit-member is a canonical non-zero ID.
func (id AcademicUnitMemberID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the class-member is a canonical non-zero ID.
func (id ClassMemberID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the external-identity is a canonical non-zero ID.
func (id ExternalIdentityID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the password-credential is a canonical non-zero ID.
func (id PasswordCredentialID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the personal-access-token is a canonical non-zero ID.
func (id PersonalAccessTokenID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the user-token is a canonical non-zero ID.
func (id UserTokenID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the MFA credential is a canonical non-zero ID.
func (id MFACredentialID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the MFA recovery-code is a canonical non-zero ID.
func (id MFARecoveryCodeID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the audit-event is a canonical non-zero ID.
func (id AuditEventID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the external-login-state is a canonical non-zero ID.
func (id ExternalLoginStateID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the file-entry is a canonical non-zero ID.
func (id FileEntryID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the file-revision is a canonical non-zero ID.
func (id FileRevisionID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the file-rendition is a canonical non-zero ID.
func (id FileRenditionID) IsValid() bool { return IsValidId(string(id)) }

// IsValid reports whether the upload-lease is a canonical non-zero ID.
func (id UploadLeaseID) IsValid() bool { return IsValidId(string(id)) }

// String returns the institution wire/database representation.
func (id InstitutionID) String() string { return string(id) }

// String returns the academic-unit wire/database representation.
func (id AcademicUnitID) String() string { return string(id) }

// String returns the programme wire/database representation.
func (id ProgrammeID) String() string { return string(id) }

// String returns the programme-level wire/database representation.
func (id ProgrammeLevelID) String() string { return string(id) }

// String returns the class wire/database representation.
func (id ClassID) String() string { return string(id) }

// String returns the academic-period wire/database representation.
func (id AcademicPeriodID) String() string { return string(id) }

// String returns the exam wire/database representation.
func (id ExamID) String() string { return string(id) }

// String returns the exam-revision wire/database representation.
func (id ExamRevisionID) String() string { return string(id) }

// String returns the user wire/database representation.
func (id UserID) String() string { return string(id) }

// String returns the session wire/database representation.
func (id SessionID) String() string { return string(id) }

// String returns the session-credential wire/database representation.
func (id SessionCredentialID) String() string { return string(id) }

// String returns the role wire/database representation.
func (id RoleID) String() string { return string(id) }

// String returns the role-binding wire/database representation.
func (id RoleBindingID) String() string { return string(id) }

// String returns the affiliation wire/database representation.
func (id AffiliationID) String() string { return string(id) }

// String returns the academic-unit-member wire/database representation.
func (id AcademicUnitMemberID) String() string { return string(id) }

// String returns the class-member wire/database representation.
func (id ClassMemberID) String() string { return string(id) }

// String returns the external-identity wire/database representation.
func (id ExternalIdentityID) String() string { return string(id) }

// String returns the password-credential wire/database representation.
func (id PasswordCredentialID) String() string { return string(id) }

// String returns the personal-access-token wire/database representation.
func (id PersonalAccessTokenID) String() string { return string(id) }

// String returns the user-token wire/database representation.
func (id UserTokenID) String() string { return string(id) }

// String returns the MFA credential wire/database representation.
func (id MFACredentialID) String() string { return string(id) }

// String returns the MFA recovery-code wire/database representation.
func (id MFARecoveryCodeID) String() string { return string(id) }

// String returns the audit-event wire/database representation.
func (id AuditEventID) String() string { return string(id) }

// String returns the external-login-state wire/database representation.
func (id ExternalLoginStateID) String() string { return string(id) }

// String returns the file-entry wire/database representation.
func (id FileEntryID) String() string { return string(id) }

// String returns the file-revision wire/database representation.
func (id FileRevisionID) String() string { return string(id) }

// String returns the file-rendition wire/database representation.
func (id FileRenditionID) String() string { return string(id) }

// String returns the upload-lease wire/database representation.
func (id UploadLeaseID) String() string { return string(id) }

// MarshalText encodes the institution as its canonical string.
func (id InstitutionID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the academic-unit as its canonical string.
func (id AcademicUnitID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the programme as its canonical string.
func (id ProgrammeID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the programme-level as its canonical string.
func (id ProgrammeLevelID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the class as its canonical string.
func (id ClassID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the academic-period as its canonical string.
func (id AcademicPeriodID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the exam as its canonical string.
func (id ExamID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the exam-revision as its canonical string.
func (id ExamRevisionID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the user as its canonical string.
func (id UserID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the session as its canonical string.
func (id SessionID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the session-credential as its canonical string.
func (id SessionCredentialID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the role as its canonical string.
func (id RoleID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the role-binding as its canonical string.
func (id RoleBindingID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the affiliation as its canonical string.
func (id AffiliationID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the academic-unit-member as its canonical string.
func (id AcademicUnitMemberID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the class-member as its canonical string.
func (id ClassMemberID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the external-identity as its canonical string.
func (id ExternalIdentityID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the password-credential as its canonical string.
func (id PasswordCredentialID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the personal-access-token as its canonical string.
func (id PersonalAccessTokenID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the user-token as its canonical string.
func (id UserTokenID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the MFA credential as its canonical string.
func (id MFACredentialID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the MFA recovery-code as its canonical string.
func (id MFARecoveryCodeID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the audit-event as its canonical string.
func (id AuditEventID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the external-login-state as its canonical string.
func (id ExternalLoginStateID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the file-entry as its canonical string.
func (id FileEntryID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the file-revision as its canonical string.
func (id FileRevisionID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the file-rendition as its canonical string.
func (id FileRenditionID) MarshalText() ([]byte, error) { return marshalID(id) }

// MarshalText encodes the upload-lease as its canonical string.
func (id UploadLeaseID) MarshalText() ([]byte, error) { return marshalID(id) }

// UnmarshalText decodes and validates the institution when non-empty.
func (id *InstitutionID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseInstitutionID)
}

// UnmarshalText decodes and validates the academic-unit when non-empty.
func (id *AcademicUnitID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseAcademicUnitID)
}

// UnmarshalText decodes and validates the programme when non-empty.
func (id *ProgrammeID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseProgrammeID)
}

// UnmarshalText decodes and validates the programme-level when non-empty.
func (id *ProgrammeLevelID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseProgrammeLevelID)
}

// UnmarshalText decodes and validates the class when non-empty.
func (id *ClassID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseClassID)
}

// UnmarshalText decodes and validates the academic-period when non-empty.
func (id *AcademicPeriodID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseAcademicPeriodID)
}

// UnmarshalText decodes and validates the exam when non-empty.
func (id *ExamID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseExamID)
}

// UnmarshalText decodes and validates the exam-revision when non-empty.
func (id *ExamRevisionID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseExamRevisionID)
}

// UnmarshalText decodes and validates the user when non-empty.
func (id *UserID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseUserID)
}

// UnmarshalText decodes and validates the session when non-empty.
func (id *SessionID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseSessionID)
}

// UnmarshalText decodes and validates the session-credential when non-empty.
func (id *SessionCredentialID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseSessionCredentialID)
}

// UnmarshalText decodes and validates the role when non-empty.
func (id *RoleID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseRoleID)
}

// UnmarshalText decodes and validates the role-binding when non-empty.
func (id *RoleBindingID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseRoleBindingID)
}

// UnmarshalText decodes and validates the affiliation when non-empty.
func (id *AffiliationID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseAffiliationID)
}

// UnmarshalText decodes and validates the academic-unit-member when non-empty.
func (id *AcademicUnitMemberID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseAcademicUnitMemberID)
}

// UnmarshalText decodes and validates the class-member when non-empty.
func (id *ClassMemberID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseClassMemberID)
}

// UnmarshalText decodes and validates the external-identity when non-empty.
func (id *ExternalIdentityID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseExternalIdentityID)
}

// UnmarshalText decodes and validates the password-credential when non-empty.
func (id *PasswordCredentialID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParsePasswordCredentialID)
}

// UnmarshalText decodes and validates the personal-access-token when non-empty.
func (id *PersonalAccessTokenID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParsePersonalAccessTokenID)
}

// UnmarshalText decodes and validates the user-token when non-empty.
func (id *UserTokenID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseUserTokenID)
}

// UnmarshalText decodes and validates the MFA credential when non-empty.
func (id *MFACredentialID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseMFACredentialID)
}

// UnmarshalText decodes and validates the MFA recovery-code when non-empty.
func (id *MFARecoveryCodeID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseMFARecoveryCodeID)
}

// UnmarshalText decodes and validates the audit-event when non-empty.
func (id *AuditEventID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseAuditEventID)
}

// UnmarshalText decodes and validates the external-login-state when non-empty.
func (id *ExternalLoginStateID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseExternalLoginStateID)
}

// UnmarshalText decodes and validates the file-entry when non-empty.
func (id *FileEntryID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseFileEntryID)
}

// UnmarshalText decodes and validates the file-revision when non-empty.
func (id *FileRevisionID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseFileRevisionID)
}

// UnmarshalText decodes and validates the file-rendition when non-empty.
func (id *FileRenditionID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseFileRenditionID)
}

// UnmarshalText decodes and validates the upload-lease when non-empty.
func (id *UploadLeaseID) UnmarshalText(data []byte) error {
	return unmarshalID(id, data, ParseUploadLeaseID)
}

// MarshalJSON encodes the institution as a JSON string.
func (id InstitutionID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the academic-unit as a JSON string.
func (id AcademicUnitID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the programme as a JSON string.
func (id ProgrammeID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the programme-level as a JSON string.
func (id ProgrammeLevelID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the class as a JSON string.
func (id ClassID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the academic-period as a JSON string.
func (id AcademicPeriodID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the exam as a JSON string.
func (id ExamID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the exam-revision as a JSON string.
func (id ExamRevisionID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the user as a JSON string.
func (id UserID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the session as a JSON string.
func (id SessionID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the session-credential as a JSON string.
func (id SessionCredentialID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the role as a JSON string.
func (id RoleID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the role-binding as a JSON string.
func (id RoleBindingID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the affiliation as a JSON string.
func (id AffiliationID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the academic-unit-member as a JSON string.
func (id AcademicUnitMemberID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the class-member as a JSON string.
func (id ClassMemberID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the external-identity as a JSON string.
func (id ExternalIdentityID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the password-credential as a JSON string.
func (id PasswordCredentialID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the personal-access-token as a JSON string.
func (id PersonalAccessTokenID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the user-token as a JSON string.
func (id UserTokenID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the MFA credential as a JSON string.
func (id MFACredentialID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the MFA recovery-code as a JSON string.
func (id MFARecoveryCodeID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the audit-event as a JSON string.
func (id AuditEventID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the external-login-state as a JSON string.
func (id ExternalLoginStateID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the file-entry as a JSON string.
func (id FileEntryID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the file-revision as a JSON string.
func (id FileRevisionID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the file-rendition as a JSON string.
func (id FileRenditionID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// MarshalJSON encodes the upload-lease as a JSON string.
func (id UploadLeaseID) MarshalJSON() ([]byte, error) { return marshalIDJSON(id) }

// UnmarshalJSON decodes a JSON string into the institution.
func (id *InstitutionID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseInstitutionID)
}

// UnmarshalJSON decodes a JSON string into the academic-unit.
func (id *AcademicUnitID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseAcademicUnitID)
}

// UnmarshalJSON decodes a JSON string into the programme.
func (id *ProgrammeID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseProgrammeID)
}

// UnmarshalJSON decodes a JSON string into the programme-level.
func (id *ProgrammeLevelID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseProgrammeLevelID)
}

// UnmarshalJSON decodes a JSON string into the class.
func (id *ClassID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseClassID)
}

// UnmarshalJSON decodes a JSON string into the academic-period.
func (id *AcademicPeriodID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseAcademicPeriodID)
}

// UnmarshalJSON decodes a JSON string into the exam.
func (id *ExamID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseExamID)
}

// UnmarshalJSON decodes a JSON string into the exam-revision.
func (id *ExamRevisionID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseExamRevisionID)
}

// UnmarshalJSON decodes a JSON string into the user.
func (id *UserID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseUserID)
}

// UnmarshalJSON decodes a JSON string into the session.
func (id *SessionID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseSessionID)
}

// UnmarshalJSON decodes a JSON string into the session-credential.
func (id *SessionCredentialID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseSessionCredentialID)
}

// UnmarshalJSON decodes a JSON string into the role.
func (id *RoleID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseRoleID)
}

// UnmarshalJSON decodes a JSON string into the role-binding.
func (id *RoleBindingID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseRoleBindingID)
}

// UnmarshalJSON decodes a JSON string into the affiliation.
func (id *AffiliationID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseAffiliationID)
}

// UnmarshalJSON decodes a JSON string into the academic-unit-member.
func (id *AcademicUnitMemberID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseAcademicUnitMemberID)
}

// UnmarshalJSON decodes a JSON string into the class-member.
func (id *ClassMemberID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseClassMemberID)
}

// UnmarshalJSON decodes a JSON string into the external-identity.
func (id *ExternalIdentityID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseExternalIdentityID)
}

// UnmarshalJSON decodes a JSON string into the password-credential.
func (id *PasswordCredentialID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParsePasswordCredentialID)
}

// UnmarshalJSON decodes a JSON string into the personal-access-token.
func (id *PersonalAccessTokenID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParsePersonalAccessTokenID)
}

// UnmarshalJSON decodes a JSON string into the user-token.
func (id *UserTokenID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseUserTokenID)
}

// UnmarshalJSON decodes a JSON string into the MFA credential.
func (id *MFACredentialID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseMFACredentialID)
}

// UnmarshalJSON decodes a JSON string into the MFA recovery-code.
func (id *MFARecoveryCodeID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseMFARecoveryCodeID)
}

// UnmarshalJSON decodes a JSON string into the audit-event.
func (id *AuditEventID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseAuditEventID)
}

// UnmarshalJSON decodes a JSON string into the external-login-state.
func (id *ExternalLoginStateID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseExternalLoginStateID)
}

// UnmarshalJSON decodes a JSON string into the file-entry.
func (id *FileEntryID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseFileEntryID)
}

// UnmarshalJSON decodes a JSON string into the file-revision.
func (id *FileRevisionID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseFileRevisionID)
}

// UnmarshalJSON decodes a JSON string into the file-rendition.
func (id *FileRenditionID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseFileRenditionID)
}

// UnmarshalJSON decodes a JSON string into the upload-lease.
func (id *UploadLeaseID) UnmarshalJSON(data []byte) error {
	return unmarshalIDJSON(id, data, ParseUploadLeaseID)
}
