// Copyright 2026 SudoSylabs
// SPDX-License-Identifier: AGPL-3.0-only

package app

import (
	"context"
	"sync"

	"github.com/sudosylabs/proctor/server/model"
)

// authorizationDecision is a short-lived, request-bound receipt produced
// after an API preflight. proof is generated by the application authorization
// service and is never serialized or accepted from clients.
type authorizationDecision struct {
	userID       string
	sessionID    string
	credentialID string
	action       model.Action
	resource     model.Resource
	requestID    string
	authorizedAt int64
	expiresAt    int64
	proof        string
}

type authorizationDecisionContextKey struct{}

type authorizationDecisionState struct {
	mu       sync.Mutex
	decision authorizationDecision
	consumed bool
}

func contextWithAuthorizationDecision(
	ctx context.Context,
	decision authorizationDecision,
) context.Context {
	return context.WithValue(
		ctx,
		authorizationDecisionContextKey{},
		&authorizationDecisionState{decision: decision},
	)
}

// consumeAuthorizationDecision returns the attached receipt at most once.
// Invalid or mismatched receipts are still consumed and force a fresh
// authorization evaluation.
func consumeAuthorizationDecision(
	ctx context.Context,
) (authorizationDecision, bool) {
	state, ok := ctx.Value(authorizationDecisionContextKey{}).(*authorizationDecisionState)
	if !ok || state == nil {
		return authorizationDecision{}, false
	}
	state.mu.Lock()
	defer state.mu.Unlock()
	if state.consumed {
		return authorizationDecision{}, false
	}
	state.consumed = true
	return state.decision, true
}
